### ISSUE TITLE
Recent clone

### ISSUE THREAD

**Issue by mowgli** [zdharma-continuum/zinit#1]
Hi,

I was shocked when I find the repo not syncing anymore and found your fork.

I have a recent clone of zinit with all branches. If you are interested, I can push it somewhere or send you a bundle. Just reach out for me by mail. :-D

**Comment by alirioguerra** [comment]
please, do it. Save us 🆘

**Comment by mowgli** [comment]
I have cloned and pushed --mirror to https://github.com/mowgli/zinit. Can you use it that way?

Please tell me when I could remove the clone again.

**Comment by alichtman** [comment]
You can remove it.
