### ISSUE TITLE
🐞 bug: the zinit installer file does not take $ZDOTDIR into consideration

### ISSUE THREAD

**Issue by tristanlukens** [zdharma-continuum/zinit#133]
### Issue description

The zinit installer file does not take `$ZDOTDIR` into consideration; it sources the zinit files in `$HOME/.zshrc`, which I think should be `$ZDOTDIR/.zshrc`.

I like putting my zsh config files in `$HOME/.config/zsh`. You can do this by putting `ZDOTDIR=$HOME/.config/zsh` which in my case is symlinked to `$HOME/dotfiles`.

When I installed zinit this morning it didn't work. After a while I stumbled upon .zshrc in my `$HOME` and thought it wasn't right, so a solution was to put the auto installed stuff into another file and source it in my own .zshrc. This is not ideal because when updating, I need to recopy this whole thing (to futureproof the sourcing added to .zshrc by the installer). I am working on a shell script to automate this, but it's an annoyance which can be fixed by changing a file path in the install script.

If `$ZDOTDIR` is unset, it will just use `$HOME`.

I have not changed any settings/installed any plugins yet, so the zinit config is what the form default is. If I need to change anything, please say. I am only an aspiring shell scripting expert, not one yet :)

Anyway, I think the installer should put the zshrc stuff in `$ZDOTDIR/.zshrc` instead of `$HOME/.zshrc`.

If I have missed anything, I will do my best to tell anyone about my system. I am currently reworking on my dotfiles, but when I'm done, I will publicise my dotfiles.

### zinit config

```zsh
zinit \
  null \
  atclone'true' \
  for zdharma_continuum/null
```

### zinit version or commit ID

9ee45d6804fdf4972a9e913a1ad86d77de124231

### zsh version

5.8

### host info

OSTYPE=darwin20.0 CPUTYPE=arm64 MACHTYPE=x86_64 LC_CTYPE=UTF-8

**Comment by alichtman** [comment]
I've observed similar behavior on my own. I have a weird hack in my .zshrc and .zshenv to get the desired behavior. 

https://github.com/alichtman/dotfiles/blob/master/.config/zsh/.zshrc#L43

https://github.com/alichtman/dotfiles/blob/master/.zshenv#L119-L129

**Comment by alichtman** [comment]
> The zinit installer file does not take $ZDOTDIR into consideration; it sources the zinit files in $HOME/.zshrc, which I think should be $ZDOTDIR/.zshrc.

Yeah, good catch. Happy to merge a PR

**Comment by tristanlukens** [comment]
Hmm. Yeah, I guess I'll look into it. I might have done something wrong! I look into reinstalling later when I have time
