### ISSUE TITLE
🐞 bug: Command not found: ^M when sourcing the zinit.zsh on Ubuntu 20.04 under WSL2

### ISSUE THREAD

**Issue by giulianisanches-inbev** [zdharma-continuum/zinit#134]
### Issue description

I'm trying to use zinit on my Ubuntu 20.04 LTS  running under WSL2 on Windows and I'm getting the following error:

```
/home/giuliani/.zinit/bin/zinit.zsh:3: command not found: ^M
/home/giuliani/.zinit/bin/zinit.zsh:7: command not found: ^M
/home/giuliani/.zinit/bin/zinit.zsh:typeset:8: not valid in this context: ZINIT_RUN^M
```

I've tried to find and remove any control character, but there is no such character.

### zinit config

The error happens as soon as I run the `source ~/.zinit/bin/zinit.zsh`. Anyways, these are the plugins/ices that I'm planning to use:

```
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting
# Load the pure theme, with zsh-async library that's bundled with it.
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure
```

### zinit version or commit ID

9ee45d6804fdf4972a9e913a1ad86d77de124231

### zsh version

5.8

### host info

HOSTTYPE=x86_64 CPUTYPE=x86_64 MACHTYPE=x86_64 OSTYPE=linux-gnu 5.10.16.3-microsoft-standard-WSL2 VERSION="20.04.3 LTS (Focal Fossa)" ID=ubuntu

**Comment by alichtman** [comment]
This can be caused by Windows line endings.

```
zinit on  main took 11s
04:03:51 AM ➜ dos2unix zinit.zsh
dos2unix: converting file zinit.zsh to Unix format...

zinit on  main took 2ms
04:03:56 AM ➜ gst
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Not seeing them here though.

**Comment by giulianisanches-inbev** [comment]
Found a solution.

My ` git config --global core.autocrlf` was set to `true`. After set it to `false` (` git config --global core.autocrlf false`) I just cloned the repository again and everything worked.

Thanks for the help.

**Comment by AndreKunitz** [comment]
Confirmed. This solved the problem! 
Thank you!
