### ISSUE TITLE
wrong packages url in .zinit-get-package

### ISSUE THREAD

**Issue by r4lv** [zdharma-continuum/zinit#14]
**Describe the bug**

I am not able to install packages using the `pack""` ice — I assume this is because the `.zinit-get-package` function has the wrong URL prefix `zinit-package-...` hardcoded:

https://github.com/zdharma-continuum/zinit/blob/e2b553ba5caabcf7ab4a31a7b31ae03ce66f3820/zinit-install.zsh#L127

while the packages live under `zsh-package-...`, e.g. https://github.com/zdharma-continuum/zsh-package-fzf

**To Reproduce**

I have the following in my .zshrc
``` sh
zinit wait"1" lucid if'[[ -z "$commands[fzf]" ]]' pack"bgn-binary+keys" for fzf
```

I get the following output when I open a new shell:

``` text
.zinit-get-package:25: datei oder Verzeichnis nicht gefunden: /tmp/tmp.06wsNmEHUB                                       
Error: the package `fzf` couldn't be found.
```

**Expected behavior**

Correcting the URL in `zinit-install.zsh`, and deleting the compiled `.zwc` fix this issue, and the packages install as expected.

**Versions:**
 - $ZSH_VERSION == `5.7.1`
 - Operating system name and version (uname -a): `Linux pi4 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`

**Comment by pschmitt** [comment]
Oh no, I named the repos wrong. Will fix asap.

**Comment by pschmitt** [comment]
I don't get how I didn't catch that during my tests...
Anyway I renamed all the repositories..! Sorry for that.
