### ISSUE TITLE
zinit drop me to a plugin directory after iTerm2 restored session from a system reboot

### ISSUE THREAD

**Issue by rainux** [zdharma-continuum/zinit#144]
I've been using iTerm2's [session restoration feature](https://iterm2.com/documentation-restoration.html) for a long time, and have a habit of keep 9 tabs open so I can quickly switch between them for different jobs.

After a system reboot, though iTerm2 can't fully restore the session according to the above documentation, but it can always keep each tab in the original directory. But after I use zinit, reboot system may drop me to a plugin directory of zinit, as the screenshot shows.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/13707/146214861-99d192e0-e4a2-4dd4-b503-30a728022083.png">

_Originally posted by @rainux in https://github.com/zdharma-continuum/zinit/discussions/139_

**Comment by vladdoster** [comment]
Could you open a new issue and use the bug template so we have more info?

Here is a link directly to a [new issue using the bug template](https://github.com/zdharma-continuum/zinit/issues/new?assignees=&labels=%F0%9F%90%9E+bug%2C%F0%9F%8E%B2+triage&template=bug-report.yml&title=%F0%9F%90%9E+bug%3A+).

**Comment by rainux** [comment]
Sorry I didn't noticed we have a template for that, will do it.
