### ISSUE TITLE
zi update fail🐞 bug: 

### ISSUE THREAD

**Issue by wbmins** [zdharma-continuum/zinit#146]
### Issue description

 zi update
Assuming --all is passed
Updating Zinit…
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token
instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: 'https://github.com/zdharma/zinit.git/' 
**_Description Update failed due to user name change_**
zdharmazdharma
zdharma  -->  zdharma-continuum

### zinit config

```zsh
zinit \
  null \
  atclone'true' \
  for zdharma_continuum/null
```

### zinit version or commit ID

9ea1c9bcb7a5ffc893eb09f1ee355e5cee8d1e6d

### zsh version

5.8

### host info

XDG_SESSION_TYPE=tty OSTYPE=linux-gnu LC_CTYPE=zh_CN.UTF-8 CPUTYPE=x86_64 MACHTYPE=x86_64 5.15.10-arch1-1 ID=arch

**Comment by pschmitt** [comment]
This here org is named zdharma-continuum, not zdharma_continuum
