### ISSUE TITLE
🐞 bug: Broken images in documentation

### ISSUE THREAD

**Issue by qubidt** [zdharma-continuum/zinit#188]
### Proposal

Just nitpicking because it bothers me to see the image placeholder. 
The images in the `README.md` are broken. They're referencing files in an `images` branch that doesn't exist in this version of the repo:

* https://github.com/zdharma-continuum/zinit/blob/d1cb4e2b47cee6f298c59b35954f45aba9c26246/README.md?plain=1#L3
* https://github.com/zdharma-continuum/zinit/blob/d1cb4e2b47cee6f298c59b35954f45aba9c26246/README.md?plain=1#L79

Also, these lines in `doc/CHANGELOG.md` also still link to the original repo, as well as reference files in the `images` branch: 

* https://github.com/zdharma-continuum/zinit/blob/d1cb4e2b47cee6f298c59b35954f45aba9c26246/doc/CHANGELOG.md?plain=1#L492
* https://github.com/zdharma-continuum/zinit/blob/d1cb4e2b47cee6f298c59b35954f45aba9c26246/doc/CHANGELOG.md?plain=1#L504
* https://github.com/zdharma-continuum/zinit/blob/d1cb4e2b47cee6f298c59b35954f45aba9c26246/doc/CHANGELOG.md?plain=1#L631

I have uploaded a copy of that branch from an old backup I found: https://github.com/qubidt/zinit/tree/images
The last commit was from 2020-02-22, so not sure if that represents the latest version of it or not, but all the filenames I can find references for exist in that branch.

**Comment by pschmitt** [comment]
Dear fellow maintainers, who deleted the images branch and why? ⁉️
@vladdoster @alichtman

**Comment by alichtman** [comment]
Didn't touch it. I bet we have an action log on the repo somewhere in settings.

**Comment by pschmitt** [comment]
The activity feed of the org does not seem to go back enough. It doesn't show up here: https://github.com/orgs/zdharma-continuum/dashboard

Thankfully we are mirroring this repo to gitlab.

[I've restored the branch]()

**Comment by qubidt** [comment]
links in CHANGELOG are still broken fyi
