### ISSUE TITLE
za-rust-atclone-handler:8

### ISSUE THREAD

**Issue by vintingb** [zdharma-continuum/zinit#19]
**Screenshots**
![image](https://user-images.githubusercontent.com/54710337/140612901-a72071c9-354a-409e-9ecf-c30612777123.png)

**Versions:**
 - $ZSH_VERSION == zsh 5.0.2 (x86_64-redhat-linux-gnu)
 - Operating system name and version (uname -a): Centos 7

No matter if I install themes or plug-ins, it always prompts like this：
```
za-rust-atclone-handler:8: array parameter za_rust_ef created globally in function
```
Neither the theme nor the plugin works.

By the way, I don’t have root privileges.

**Comment by pschmitt** [comment]
This is 100% percent due to the fact that you are using a seriously out-of-date version of zsh.
If you cannot update the packaged version you may want to:

```zsh
zinit pack"5.8" for zsh
```

in your zshrc.

**Comment by pschmitt** [comment]
Nevermind, your ZSH version isn't the culprit after all. I was wrong.

I tried reproducing your issue inside a `centos:7` container. I couldn't:

![Screenshot_20211107-012300.png](https://user-images.githubusercontent.com/37886/140627718-042b5c56-18d8-4f33-aa16-424961e61646.png)

Did you perhaps forget to `promptinit`?

**Comment by pschmitt** [comment]
`z-a-rust` seems to be genuinely incompatible though.

**Comment by vintingb** [comment]
> Nevermind, your ZSH version isn't the culprit after all. I was wrong.
> 
> I tried reproducing your issue inside a `centos:7` container. I couldn't:
> 
> ![Screenshot_20211107-012300.png](https://user-images.githubusercontent.com/37886/140627718-042b5c56-18d8-4f33-aa16-424961e61646.png)
> 
> Did you perhaps forget to `promptinit`?

Thanks! I add autoload -U promptinit to zshrc. It. is working.
