### ISSUE TITLE
🐞 bug: OMZP::per-directory-history doesn't install correctly

### ISSUE THREAD

**Issue by galou** [zdharma-continuum/zinit#195]
### Issue description

It looks that zinit has some issues installing OMZP::per-directory-history. When I open a new terminal, I get the error message `per-directory-history.zsh command not found`. Maybe zinit has some issues with the symbolic link?

In the directory `snippets/OMZP::per-directory-history` I get the file `OMZP::per-directory-history` (and its compiled counterpart) containing the text `per-directory-history.zsh`.

### zinit config

Sorry I don't understand the question, the relevant part of my config is
```
zinit wait lucid for  OMZP::per-directory-history
```

### zinit version or commit ID

bc1bedb59013eaec0b63abde6d6131bd64642eb0

### zsh version

zsh 5.8 (x86_64-ubuntu-linux-gnu)

### host info

XDG_SESSION_TYPE=x11 OSTYPE=linux-gnu CPUTYPE=x86_64 MACHTYPE=x86_64 5.13.0-28-generic VERSION="20.04.4 LTS (Focal Fossa)" ID=ubuntu

**Comment by galou** [comment]
OK, thanks! Sorry for the noise!

**Comment by vladdoster** [comment]
@galou No worries. Here it is working:

<img width="2048" alt="Screen Shot 2022-03-11 at 07 49 54" src="https://user-images.githubusercontent.com/10052309/157880307-e586fc23-68b7-49ee-95a6-a6b089a68a97.png">
