### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by caiopratali** [zdharma-continuum/zinit#2]
Hello Everything is fine?

You're probably migrating the repository project and it's giving several errors in the installation, I think it's because the url zinit-zsh has changed...

**Comment by mguidoti** [comment]
Yep, I'm getting the same issue. Most likely related to the migration of repos. 

![image](https://user-images.githubusercontent.com/44419136/139606443-a90a4b04-3503-4f01-a4c3-27796c581d42.png)

**Comment by alichtman** [comment]
You need to update your `.zshrc` to point to `zdharma-continuum/fast-syntax-highlighting`.

**Comment by findNextStep** [comment]
can we update the zdharma to zdharma-continuum?

**Comment by alichtman** [comment]
They're your configuration files. You can change them whenever you'd like.

And you're going to have to change them if you want `fast-syntax-highlighting` to work.

**Comment by findNextStep** [comment]
> 它们是您的配置文件。您可以随时更改它们。
> 
> 如果你想`fast-syntax-highlighting`工作，你将不得不改变它们。
> 
> 您需要进行此更改：[alichtman/dotfiles@ 1d03e8e](https://github.com/alichtman/dotfiles/commit/1d03e8e1b76342f95a2e3d22bbfcf2fb08fdf9c6)

I think we need at least update readme.md in this repo to avoid others issure

**Comment by alichtman** [comment]
Yeah, that's reasonable. Want to submit a PR?

**Comment by findNextStep** [comment]
ok, let me do this

**Comment by alichtman** [comment]
@vladdoster  Took care of it in #4.
