### ISSUE TITLE
docs:  Migration instructions (GH wiki) breaks Zinit

### ISSUE THREAD

**Issue by Louis2747** [zdharma-continuum/zinit#207]
### Discussed in https://github.com/zdharma-continuum/zinit/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **lebr0nli** January 25, 2022</sup>
I follow the wiki (🚚 Migration to zdharma continuum):
```
zinit light-mode for \                                                      
    zdharma-continuum/zinit-annex-readurl \                              
    zdharma-continuum/zinit-annex-bin-gem-node \                            
    zdharma-continuum/zinit-annex-patch-dl \                                
    zdharma-continuum/zinit-annex-rust
```

But keep getting the following error:

```
Downloading  _unknown … (at label:  …)
fatal: destination path '/root/.local/share/zinit/plugins' already exists and is not an empty directory.

Clone failed (code: 128).
/root/.zshrc:78: no such file or directory: zdharma-continuum/zinit-annex-readurl
/root/.zshrc:79: no such file or directory: zdharma-continuum/zinit-annex-bin-gem-node
/root/.zshrc:80: no such file or directory: zdharma-continuum/zinit-annex-patch-dl
/root/.zshrc:81: no such file or directory: zdharma-continuum/zinit-annex-rust
```

Does anyone know how to fix it?</div>
I also had this problem, what fixed it for me was removing the spaces after the backslashes.
So I think the best solution would be to just remove the extra spaces from the wiki.

**Comment by vladdoster** [comment]
@Louis2747 Fixed [here](https://github.com/zdharma-continuum/zinit/wiki/%F0%9F%9A%9A-Migration-to-zdharma-continuum/_compare/70a62a624b849aebe0cf9d0d87b134c628227c0a#diff-9283b6cbe3a4731756ada5543c6cf34e85627fd1ac51cea99b69b8236739d4a2R17-R18)
