### ISSUE TITLE
🎁 Feature request: Allow for checksum

### ISSUE THREAD

**Issue by hoshsadiq** [zdharma-continuum/zinit#210]
### Feature request

It would be nice to have a method to validate checksums. Perhaps it's should be an annex but I think having it built-in seems more reasonable.

There's a certain format many people use when uploading binaries (at least, to GitHub). It's usually along the lines of `<filename>.<sum>`, and potentially a `<filename>.sig` file too. From there zinit can then validate using the relevant binaries, and if a `.sig` is available, a key is provided, and GPG binaries are available, zinit can create a new gpg home directory, import the key from a keyserver and then validate the binaries.

**Comment by vladdoster** [comment]
See #292
