### ISSUE TITLE
sh: 210: Bad substitution

### ISSUE THREAD

**Issue by ununhexium** [zdharma-continuum/zinit#217]
The automated install runs the script with `sh` but bash is needed for `scripts/install.sh`

Doing `bash -c "$(curl -fsSL https://git.io/zinit-install)"` works.

**Comment by vladdoster** [comment]
Are you sure that is the issue? The installer has a `bash` shebang, [see here](https://github.com/zdharma-continuum/zinit/blob/main/scripts/install.sh#L1).

**Comment by vladdoster** [comment]
Oh, I see the docs aren't up to date. Pushing a docs update now.

**Comment by vladdoster** [comment]
@ununhexium Thanks for catching this so quickly! I opened PR #218 accordingly.

**Comment by vladdoster** [comment]
Updated docs, see [here](https://github.com/zdharma-continuum/zinit#automatic-installation-recommended).
