### ISSUE TITLE
[bug]: Commit d59f150 filters appimages from Github release assets

### ISSUE THREAD

**Issue by LarsHaalck** [zdharma-continuum/zinit#228]
### Describe the bug

Using `bpick"*appimage*"`no longer works as of d59f15067eeeb97ac0695066115cf6abb46075e5 as can be seen here [d59f15067eeeb97ac0695066115cf6abb46075e5/zinit-install.zsh#L1489](https://github.com/zdharma-continuum/zinit/blob/d59f15067eeeb97ac0695066115cf6abb46075e5/zinit-install.zsh#L1489)

### Steps to reproduce

```zsh
zinit ice wait lucid from"gh-r" as"null" bpick"*appimage*" sbin"nvim* -> nvim" ver="stable"
zinit light neovim/neovim
```

### Expected behavior

Prior to d59f15067eeeb97ac0695066115cf6abb46075e5, the above command would select `nvim.appimage`. This is now filtered out, selecting `nvim.appimage.zsync`.

### OS / Linux distribution

Arch Linux (5.17.3)

### Zsh version

5.8

### Terminal emulator

Alacritty

**Comment by vladdoster** [comment]
You shouldn't need to use bpick anymore as the updates improved gh-r logic. Unless there is 
 a particular reason for using AppImage, try the following recipe:

```zsh
zinit from'gh-r' sbin'**/nvim' ver'stable' for neovim/neovim
```

**Comment by LarsHaalck** [comment]
Ah yes you are right. I think I had to install the appimage on some older neovim version on a very old remote machine. Your recipe works fine for neovim thanks. 

But if I understand the code correctly, on a project that has only a single appimage asset, it will be filtered out and there is no way for the user to `bpick` it manually right?

**Comment by LarsHaalck** [comment]
Thanks for the detailed explanations. I fully understand and I think for all my use cases, I can live without Appimages, but I think the user, nevertheless, should have to option to explicitly request it (e.g, to allow it as a last resort). But if this is the consensus and/or if has been discussed elsewhere, I think we can close this issue. Thanks.

**Comment by vladdoster** [comment]
@LarsHaalck 

There was an issue with the regex (unrelated to AppImages, however), and went ahead to include a fix to this issue. I also added tests to avoid future regressions.

See #244
