### ISSUE TITLE
[bug]: load docker-compose from `gh-r` on x86_64 selected wrong architecture

### ISSUE THREAD

**Issue by pigoil** [zdharma-continuum/zinit#247]
### Describe the bug

I'm trying to load docker-compose bin from `gh-r` on a x86_64 machine, however, zinit seems to select the ppc64le version:

```
Downloading docker/compose...
(Requesting `docker-compose-linux-ppc64le'...)
```

When I run `docker-compose -v`, it gives me:

```
$ docker-compose -v
zsh: exec format error: docker-compose
```

### Steps to reproduce

1. add these line in .zshrc as zinit's wiki do on a x86_64 machine:
    ```
    zinit ice from"gh-r" as"program" mv"docker* -> docker-compose"
    zinit load docker/compose
    ```
2. run `source .zshrc`
3. run `docker-compose -v`

### Expected behavior

select [docker-compose-linux-x86_64](https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64) version

### OS / Linux distribution

linux-gnu ubuntu

### Zsh version

5.4.2

### Terminal emulator

GNOME Terminal

**Comment by vladdoster** [comment]
<img width="867" alt="Screen Shot 2022-05-05 at 04 13 14" src="https://user-images.githubusercontent.com/10052309/166894515-6a0af26c-23b4-4b92-a4ff-9f1330312db7.png">

This is a known issue with an open PR to address it.

1. https://github.com/zdharma-continuum/zinit/issues/225
2. https://github.com/zdharma-continuum/zinit/pull/235

**Comment by pigoil** [comment]
i see, thanks for the reply

**Comment by vladdoster** [comment]
@pigoil Could you try the branch in PR #235 and let me know if it fixes your issue?

**Comment by vladdoster** [comment]
https://github.com/zdharma-continuum/zinit/runs/6316146273?check_suite_focus=true#step:8:1430

**Comment by pigoil** [comment]
> @pigoil Could you try the branch in PR #235 and let me know if it fixes your issue?

yes, it works :100: , i have tested it on both my physical machine & docker container.

**Comment by vladdoster** [comment]
@pigoil  , thank you for responding so quickly! Glad to hear it fixes the issue. Should be merged within 24 hours.

**Comment by vladdoster** [comment]
Merged
