### ISSUE TITLE
[bug]: missing file for the macos plugin of oh my zsh

### ISSUE THREAD

**Issue by yanxiang-wang** [zdharma-continuum/zinit#255]
### Describe the bug

```
/Users/aaa/.local/share/zinit/snippets/OMZP::macos/OMZP::macos:source:265: no such file or directory: /Users/aaa/.local/share/zinit/snippets/OMZP::macos/music
/Users/aaa/.local/share/zinit/snippets/OMZP::macos/OMZP::macos:source:268: no such file or directory: /Users/aaa/.local/share/zinit/snippets/OMZP::macos/spotify
(base)
```

### Steps to reproduce

```
zinit wait lucid for \
      OMZP::colored-man-pages \
      OMZP::cp \
      OMZP::extract \
      OMZP::fancy-ctrl-z \
      OMZP::git \
      OMZP::sudo \
      OMZP::macos
```

### Expected behavior

missing the third party scripts

### OS / Linux distribution

MacOS 12.0.1

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by vladdoster** [comment]
This is not a bug. Additionally, the instructions to properly install plugins that require files is documented in the README.md.

See [here](https://github.com/zdharma-continuum/zinit#migration)
