### ISSUE TITLE
[bug]: Starship Install "no such file or directory: atclone./starship init zsh > init.zsh; ./starship completions zsh > _starship":

### ISSUE THREAD

**Issue by EmDash00** [zdharma-continuum/zinit#271]
### Describe the bug

I'm new to using zinit having just switched from OMZ yesterday. I was testing out having zinit manage the install for Starship; however, it appears to error.  appears that putting

### Steps to reproduce

The example on the repository's README.md states these lines should do the trick.

```
zinit ice as"command" from"gh-r" \ 
          atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
          atpull"%atclone" src"init.zsh"
zinit light starship/starship
```

However, when I just pasted them in, I got the above error. There appears to be something wrong with the substitution perhaps.

### Expected behavior

I expect it to not error during the atclone step. 

### OS / Linux distribution

Linux-GNU / Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

Termite

**Comment by EmDash00** [comment]
It appears raw copying the text leaves some improper whitespace characters. Deleting them and reinserting tabs or spaces seems to solve the problem.

**Comment by vladdoster** [comment]
Ah, glad you got it figured out. Indeed that was the issue, which you can see below.

<img width="1100" alt="Screen Shot 2022-05-14 at 03 49 03" src="https://user-images.githubusercontent.com/10052309/168418528-ef04c5c3-3a89-49c6-a39f-91716a1dd0cc.png">

Additionally, here is how I would write the starship recipe

```zsh
zinit for as'completion' atclone"
      ./starship init zsh > init.zsh
      ./starship completions zsh > _starship" \
    from"gh-r" nocompile sbin src"init.zsh" \
  starship/starship
```

**Comment by vladdoster** [comment]
zinit ice as"command" from"gh-r" \
    atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
    atpull"%atclone" src"init.zsh"
zinit light starship/starship

**Comment by vladdoster** [comment]
The benefit being that you avoid adding starship to your path, are more explicit about the completion, and remove ices (`atpull`) that aren't needed.

**Comment by jankatins** [comment]
> remove ices (atpull) that aren't needed

Why is that not needed? If starship changes the init code, I want to get the updated code on update and I though atpull would run on update, not atclone? Or is that different for gh-r?
