### ISSUE TITLE
[bug]: (eval):25: defining function based on alias `zi'

### ISSUE THREAD

**Issue by Dhamma-valence** [zdharma-continuum/zinit#276]
### Describe the bug

By default, I get this error message when first starting zsh (after installing zinit).
```
(eval):25: defining function based on alias `zi'
(eval):25: parse error near `()'
```

I've finally found that it's sourced from line 3065 of `zinit.zsh`
```
builtin alias zpl=zinit zplg=zinit zi=zinit zini=zinit
```

Removing `zi=zinit` _does_ fix it, but I'm concerned that this alias may be used elsewhere and simply removing it may break something.

### Steps to reproduce

1. Install zinit the automated way.
2. Start zsh
3. Get error

### Expected behavior

I expect to not get the error

### OS / Linux distribution

linux-musl pc (It's Debian Sid/Unstable)

### Zsh version

zsh 5.8.1 (x86_64-debian-linux-gnu)

### Terminal emulator

Alacritty

**Comment by vladdoster** [comment]
@Dhamma-valence What is your zinit configuration?

**Comment by vladdoster** [comment]
The reason I ask is I have a hunch that something (i.e., plugin, alias, etc.) you use is creating the conflict.

Even though your solution might fix the problem, there are a few issues with it. The issues are not specific to Zinit, but building software with end-users overall. 

Let's assume Zinit users use the 4 possible aliases equally (25% of users per alias)

1. You'd immediately break 25% of user configurations for no reason.
2. Do we wait until the same issue inevitably crops up with the `zini` and `zpl` aliases, and remove those as well? If we removed all three at once, we break 75% of configurations.
3. The root issue isn't being addressed. What about `zi` breaks zinit?

Don't take this as me trying to belittle you, but as my thought process. This is a small project, but a great example is the Google SRE podcast that details how to approach large-scale migrations while optimizing for user experience. They migrated 1+ million endpoints while requiring no changes or downtime for customers.

[sre-prodcast-01-05.pdf](https://github.com/zdharma-continuum/zinit/files/8749717/sre-prodcast-01-05.pdf)

**Comment by vladdoster** [comment]
@Dhamma-valence Any update on this?

**Comment by Dhamma-valence** [comment]
Sorry, I've been busy with my own projects. I spent some time trying to actually find the root cause using [zshdb](https://github.com/rocky/zshdb/) as a debugger, but I'm not exactly well versed in debuggers and would need time to learn how to use it so I've not come back to it just yet.

**Comment by Dhamma-valence** [comment]
Ah yes, PR #280 does seem to fix this. Thank you for that! This has been a bug for as long as I've used zinit so it's good to see it quashed.

**Comment by briandunn** [comment]
Having the same issue - reverting to tag v3.7.0 fixed it for me.
