### ISSUE TITLE
Question: how to migrate from old zinit?

### ISSUE THREAD

**Issue by tactlessfish** [zdharma-continuum/zinit#28]
I used zinit before it was deleted, and I wanted to migrate to the new repository.
In `~/.zinit/bin`, I ran:
```
git remote set-url origin https://github.com/zdharma-continuum/zinit.git
```

It seems to have worked; `zinit self-update` pulls from the new URL.
<img width="770" alt="Screen Shot 2021-11-08 at 5 57 40 PM" src="https://user-images.githubusercontent.com/29507110/140836988-5afebe05-60fb-4e11-b5ef-674f4ba42257.png">

Is this the recommended way of migrating? Perhaps some documentation could be added to the README to help other users.

**Comment by alichtman** [comment]
It's currently covered in the [wiki](https://github.com/zdharma-continuum/zinit/wiki/Migration-to-zdharma-continuum) but happy to approve a PR. :)

**Comment by pschmitt** [comment]
> Is this the recommended way of migrating?

Pretty much, yes!

> Perhaps some documentation could be added to the README to help other users.

We need to do that, yes.

**Comment by tactlessfish** [comment]
Ah, thanks. I see the wiki page now. It looks good, but I think it should clarify that the zinit repo is by default `~/.zinit/bin`.

**Comment by pschmitt** [comment]
I'm not sure what you mean.

The installer echoes the install dir quite clearly. 

![Screenshot_20211110-203302.png](https://user-images.githubusercontent.com/37886/141180932-0e73ef4a-ae9b-476a-a101-c6aa0d665c0e.png)

**Comment by tactlessfish** [comment]
I mean in the wiki page. Currently, it says:

> 2. Set `zinit` git remote url in the zinit repo: `git remote set-url origin https://github.com/zdharma-continuum/zinit.git && git pull`

I suggest writing: 

> 2. In your `zinit` installation directory (by default `~/.zinit/bin`), set the new repository as the git remote: `git remote set-url origin https://github.com/zdharma-continuum/zinit.git`

This clarifies where to run the command and what the command does.

**Comment by pschmitt** [comment]
Ohhhh right.

Can do! Thanks.

**Comment by pschmitt** [comment]
Done!
-> https://github.com/zdharma-continuum/zinit/wiki/Migration-to-zdharma-continuum

**Comment by tactlessfish** [comment]
Thank you!

**Comment by mys721tx** [comment]
Other packages such as zdharma-continuum/fast-syntax-highlighting also needs updating.

**Comment by pschmitt** [comment]
Maybe we should provide a script to do this automagically.
