### ISSUE TITLE
[feat]: New message formatters

### ISSUE THREAD

**Issue by psprint** [zdharma-continuum/zinit#283]
### If the feature solves a problem you have, specify it here.

Debug messages are often problematic - they:
- pollute the code a little, 
- require or at least appear to require high maintenance effort,
- require a grading/message-level mechanism that enables them.

The proposed formatter `{dbg}` doesn't introduce such problems.

### Describe the proposed feature.

Zinit supports applying format codes on parts of messages. If it encounters a tag `{x}` it first looks for a function `.zinit-formatter-x` and if it's being found it calls it on text between `{x}...{...` I.e. the tag and the next tag (which can be `{rst}`) and then substitutes captured stdout.

The feature is to add a function `.zinit-formatter-dbg` that would substitute empty text if `ZINIT[DEBUG] != 1`, and the original text in opposite case.

This would allow to embed additional information to existing messages, lowering the pollution, effort and allow comfortable enabling mechanism.

### Additional context

On this occasion I would like to mention one more extension to `.zinit-message` - to allow limiting tag activity range to only one whitespace delimited word if the tag would be followed by the digit `1`. For example:

```zsh
zinit-message "Plugin {pid}A/B{rst} installed"
```
Becomes:

```zsh
zinit-message "Plugin {pid1}A/B installed"
```

**Comment by vladdoster** [comment]
@psprint Great idea and I've been wanting a clean way to add debug messages.
