### ISSUE TITLE
[feat]: Using ssh clone for load/light

### ISSUE THREAD

**Issue by c4dr01d** [zdharma-continuum/zinit#284]
### If the feature solves a problem you have, specify it here.

Since GitHub changes the authentication from password to ssh, I switch the clone method from https to ssh, when using https to download plugins is so slow and have ssl error sometimes

### Describe the proposed feature.

Maybe can add option for change the default download method, can switch to https or ssh

### Related Issues

#59

**Comment by vladdoster** [comment]
How does this differ from the pre-existing `proto` ice?

https://github.com/zdharma-continuum/zinit#cloning-options

**Comment by c4dr01d** [comment]
I just read the manual and search others snippet, I configure ssh clone worked, thanks the answer @vladdoster
