### ISSUE TITLE
[bug]: Wrong fzf binary for M1 chip

### ISSUE THREAD

**Issue by seagle0128** [zdharma-continuum/zinit#287]
### Describe the bug

Zinit downloads wrong fzf binary from Github on M1 Macbook.

### Steps to reproduce

```shell
zinit ice wait lucid from"gh-r" nocompile src'key-bindings.zsh' sbin \
      dl'https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh -> _fzf_completion;
         https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh -> key-bindings.zsh;
         https://raw.githubusercontent.com/junegunn/fzf/master/man/man1/fzf-tmux.1 -> $ZPFX/share/man/man1/fzf-tmux.1;
         https://raw.githubusercontent.com/junegunn/fzf/master/man/man1/fzf.1 -> $ZPFX/share/man/man1/fzf.1'
zinit light junegunn/fzf
```

`fzf-0.30.0-darwin_amd64.zip` is downloaed on M1 Macbook.

### Expected behavior

`fzf-0.30.0-darwin_arm64.zip` is downloaded for M1 chip.

### OS / Linux distribution

macOS M1

### Zsh version

5.8.1

### Terminal emulator

iTerm2

**Comment by vladdoster** [comment]
I'm not seeing this issue?

<img width="374" alt="Screen Shot 2022-05-28 at 21 58 51" src="https://user-images.githubusercontent.com/10052309/170850005-f0717959-53d4-481a-a4e9-96d344b107cb.png">

**Comment by vladdoster** [comment]
@seagle0128, I'm not seeing this issue?


<img width="1816" alt="Screen Shot 2022-05-28 at 22 02 02" src="https://user-images.githubusercontent.com/10052309/170850085-b8052d39-7db4-44fc-a0c6-0d147764ec72.png">

**Comment by vladdoster** [comment]
<img width="1816" alt="Screen Shot 2022-05-28 at 22 05 12" src="https://user-images.githubusercontent.com/10052309/170850146-7102123d-ec4e-4e6d-b32c-5baa7c4c9158.png">

**Comment by vladdoster** [comment]
Not to be pedantic, but `macOS M1` isn't really the OS distribution.

<img width="457" alt="Screen Shot 2022-05-28 at 22 09 00" src="https://user-images.githubusercontent.com/10052309/170850279-92f5bc52-e775-4e43-b0bb-ccd0d988cc5d.png">

**Comment by vladdoster** [comment]
Seems to work on both architectures on M1, too.

```arch -arch arm64```

and

```arch -arch x86_64```

<img width="1728" alt="Screen Shot 2022-05-29 at 00 18 37" src="https://user-images.githubusercontent.com/10052309/170853491-558ad098-c0a8-4f69-ab76-b31996ac3c19.png">

**Comment by vladdoster** [comment]
@seagle0128 Can you confirm if you still see this bug or can this issue be closed?

**Comment by seagle0128** [comment]
I still get wrong fzf binary even though I upgrade to the latest :-(

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/140797/172037772-026d1acb-5510-48b5-8417-8e5d89514d17.png">

**Comment by vladdoster** [comment]
can you try

```
zinit delete junegunn/fzf --yes \
&& rm -rf "$HOME/.local/share/zinit/zinit.git" \
&& exec zsh
```

**Comment by vladdoster** [comment]
I proved in a screenshot this isn't the issue, no?

**Comment by seagle0128** [comment]
> The issue seems to be that MACHTYPE (compiled in CPU type) is searched before CPUTYPE (runtime detected CPU type). If you launch via `/bin/zsh` from an x86_64 terminal, then MACHTYPE=x86_64 while CPUTYPE=arm64

@docwhat You are right! I am using the built-in zsh which displays:

```shell
❯ /bin/zsh --version
zsh 5.8.1 (x86_64-apple-darwin21.0)
```

**Comment by vladdoster** [comment]
I don't think this is the issue.

You are using the x86_64 version of Zsh, so it is selecting the correct binary.

I think this is more an issue of the macOS Zsh version, and I have hunch you're running Iterm2 via Rosetta2?

<img width="962" alt="Screen Shot 2022-06-08 at 15 07 05" src="https://user-images.githubusercontent.com/10052309/172707403-1ee72d96-6bef-413f-ad6d-b2222a756d1e.png">

**Comment by docwhat** [comment]
> @docwhat -- I proved in a screenshot this isn't the issue, no? 

To reproduce the bug your MACHTYPE needs to be x86_64 and CPUTYPE needs to be arm64. 

In this bug they disagree because the terminal program is x86_64 which runs /bin/zsh.

/bin/zsh is a universal binary which effectively has two binaries in it. One is compiled with MACHTYPE=x86_64 and one is compiled with MACHTYPE=arm64. 

In both cases, CPUTYPE is the same because they use the same CPU detection methods.

**Comment by vladdoster** [comment]
Yes, so the question is whether or not iterm2 was running via Rosetta2. Which would propagate to Zsh selection, right?

**Comment by docwhat** [comment]
@seagle0128's comment above implies that he has the x86_64 version of iTerm2.

In my case, Kitty only has x86_64 binaries for macOS at this time; it always runs under Rosette2.

**Comment by seagle0128** [comment]
> I think this is more an issue of the macOS Zsh version, and I have hunch you're running Iterm2 via Rosetta2?

No, I am not using x86_64 iTerm2.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/140797/172771947-97aa91a0-3c15-4c70-81b6-4591b72aa3ec.png">

**Comment by vladdoster** [comment]
Tangential, but you might want to update your version

I see:

<img width="278" alt="Screen Shot 2022-06-08 at 15 37 03" src="https://user-images.githubusercontent.com/10052309/172838397-db254bbb-f1ef-4e2a-8eee-24b26a97dd7b.png">

What is output of:

```zsh
lipo /Applications/iTerm.app/Contents/MacOS/iTerm2 -detailed_info
```

```zsh
ᐳ lipo /Applications/iTerm.app/Contents/MacOS/iTerm2 -detailed_info
Fat header in: /Applications/iTerm.app/Contents/MacOS/iTerm2
fat_magic 0xcafebabe
nfat_arch 2
architecture x86_64
    cputype CPU_TYPE_X86_64
    cpusubtype CPU_SUBTYPE_X86_64_ALL
    capabilities 0x0
    offset 16384
    size 18469472
    align 2^14 (16384)
architecture arm64
    cputype CPU_TYPE_ARM64
    cpusubtype CPU_SUBTYPE_ARM64_ALL
    capabilities 0x0
    offset 18497536
    size 17904240
    align 2^14 (16384)

~
ᐳ
```

**Comment by docwhat** [comment]
@seagle0128 when you fire up your iTerm2 and run 'echo "shell:$SHELL  compiled-cpu:$MACHTYPE  detected-cpu:$CPUTYPE"` I would expect you'd get:

```
$ echo "shell:$SHELL  compiled-cpu:$MACHTYPE  detected-cpu:$CPUTYPE"
shell:/bin/zsh  compiled-cpu:x86_64  detected-cpu:arm64
```

...which is what I get with Kitty on my M1.

**Comment by seagle0128** [comment]
```
❯ lipo /Applications/iTerm.app/Contents/MacOS/iTerm2 -detailed_info
input file /Applications/iTerm.app/Contents/MacOS/iTerm2 is not a fat file
Non-fat file: /Applications/iTerm.app/Contents/MacOS/iTerm2 is architecture: arm64
```

Before:
```shell
❯ zsh --version
zsh 5.8.1 (x86_64-apple-darwin21.0)
❯ echo "shell:$SHELL  compiled-cpu:$MACHTYPE  detected-cpu:$CPUTYPE"
shell:/bin/zsh  compiled-cpu:x86_64  detected-cpu:arm64
````

Now:
```shell
❯ zsh --version
zsh 5.9 (arm-apple-darwin21.3.0)
❯ echo "shell:$SHELL  compiled-cpu:$MACHTYPE  detected-cpu:$CPUTYPE"
shell:/usr/local/bin/zsh  compiled-cpu:arm  detected-cpu:arm64
```

**Comment by vladdoster** [comment]
@seagle0128 that makes sense. So is my previous message true or am I misunderstanding?

> I don't think this is the issue.
> 
> You are using the x86_64 version of Zsh, so it is selecting the correct binary.
> 
> I think this is more an issue of the macOS Zsh version, and I have hunch you're running Iterm2 via Rosetta2?

**Comment by seagle0128** [comment]
@vladdoster Correct. But I still think it's better checking $CPUTYPE first, for better performance. No idea why zsh(x86_64) is built-in. Maybe need documentation? Thank you!

**Comment by vladdoster** [comment]
> @vladdoster Correct. But I still think it's better checking $CPUTYPE first, for better performance. 

What program(s) have you observed with performance differences? 



> No idea why zsh(x86_64) is built-in. 

Granted it is a shell, but probably due to APIs (memory allocation) not being 1-to-1 plus x86 version being defacto target for majority of users which makes it preferable (e.g., increased stability, all features, relying on contributors to maintain 2nd version)

But probably because M1 is first generation and they will switch version at some point when Intel apple laptops are less common.


> Maybe need documentation? Thank you!

Wouldn't hurt, will add something 

> BTW, I remember two or four weeks ago, the behavior is different if I am not wrong.

Indeed, see #

**Comment by vladdoster** [comment]
@seagle0128 

lol, this just happened to be on HackerNews front page 

<img width="636" alt="Screen Shot 2022-06-11 at 02 20 41" src="https://user-images.githubusercontent.com/10052309/173177934-f5085aa5-a79a-4d4c-9343-db71ae623285.png">

HN thread: https://news.ycombinator.com/item?id=31696447

**Comment by seagle0128** [comment]
>What program(s) have you observed with performance differences?

In my env, at the first time startup, x86 binaries run slower significantly than arm binaries. e.g. rg, fzf.

**Comment by vladdoster** [comment]
> >What program(s) have you observed with performance differences?
> 
> 
> 
> In my env, at the first time startup, x86 binaries run slower significantly than arm binaries. e.g. rg, fzf.

Isn't this to be expected since it is being ran via Rosetta?

**Comment by vladdoster** [comment]
@docwhat ... this is due to quoting (i.e., `'` v.s. `"`) of variables, right? So what it reports isn't actually the value Zinit is using. 

Could I get a sanity check? Below is the output of the respective logic 😖.

<img width="1027" alt="Screen Shot 2022-06-17 at 03 13 29" src="https://user-images.githubusercontent.com/10052309/174257084-5c203585-daa6-48e5-992c-fe1ce72c8e59.png">

**Comment by vladdoster** [comment]
@seagle0128

as a temporary solution, set the following environment variable 
in your `.zshenv` or `.zprofile` or set it in your arch preferences file (`man arch`).

```zsh
export ARCHPREFERNCE=arm64e
```

**Comment by seagle0128** [comment]
@vladdoster Thank you! The workaround works!

**Comment by ngocphamm** [comment]
I'm still getting this issue with latest version of `zinit`, using `/bin/zsh` in macOS 12.6.1, which is `x86_64` built.

```
Downloading junegunn/fzf…
(Requesting `fzf-0.35.1-darwin_amd64.zip'…)
#################################################################################################################################################################################################################### 100.0%
[ziextract] Unpacking the files from: `fzf-0.35.1-darwin_amd64.zip'…
Archive:  fzf-0.35.1-darwin_amd64.zip
  inflating: fzf
[ziextract] Successfully extracted and assigned +x chmod to the file: fzf.
[patch-dl annex]: File fzf-tmux downloaded correctly
[patch-dl annex]: File completion.zsh downloaded correctly
[patch-dl annex]: File key-bindings.zsh downloaded correctly
[patch-dl annex]: File fzf-tmux.1 downloaded correctly
[patch-dl annex]: File fzf.1 downloaded correctly
bin-gem-node annex: Created the fzf shim and set +x on the fzf binary
bin-gem-node annex: Created the fzf-tmux shim and set +x on the fzf-tmux binary

Downloading ajeetdsouza/zoxide…
(Requesting `zoxide-0.8.3-x86_64-apple-darwin.tar.gz'…)
#################################################################################################################################################################################################################### 100.0%
[ziextract] Unpacking the files from: `zoxide-0.8.3-x86_64-apple-darwin.tar.gz'…
[ziextract] Successfully extracted and assigned +x chmod to the file: zoxide.
(eval):1: bad CPU type in executable: ./zoxide
Warning: ∞zinit-atclone-hook hook returned with 127
bin-gem-node annex: Created the zoxide shim and set +x on the zoxide binary
~ » echo "shell:$SHELL  compiled-cpu:$MACHTYPE  detected-cpu:$CPUTYPE"                                                                                                                                              ✘ 127
shell:/bin/zsh  compiled-cpu:x86_64  detected-cpu:arm64
```

I have tried putting `export ARCHPREFERENCE=arm64e` in `.zprofile` with no success.
