### ISSUE TITLE
Update Gitter links in all READMEs

### ISSUE THREAD

**Issue by alichtman** [zdharma-continuum/zinit#29]
We also need to standardize on a synchronous discussion platform. I set up Gitter: https://gitter.im/zdharma-continuum/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

Here's an embeddable Markdown button: `[![Gitter](https://badges.gitter.im/zdharma-continuum/community.svg)](https://gitter.im/zdharma-continuum/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)`

[![Gitter](https://badges.gitter.im/zdharma-continuum/community.svg)](https://gitter.im/zdharma-continuum/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

_Originally posted by @alichtman in https://github.com/zdharma-continuum/zinit/issues/26#issuecomment-963814890_

**Comment by pschmitt** [comment]
Here's a somewhat updated version of the badge:

```markdown
[![Gitter][gitter-image]][gitter-link]

<!--- README text --!>

[gitter-image]: https://badges.gitter.im/zdharma-continuum/community.svg
[gitter-link]: https://gitter.im/zdharma-continuum/community
```

[![Gitter][gitter-image]][gitter-link]

[gitter-image]: https://badges.gitter.im/zdharma-continuum/community.svg
[gitter-link]: https://gitter.im/zdharma-continuum/community

**Comment by pschmitt** [comment]
Should be done now.
Will merge these soon.

**Comment by pschmitt** [comment]
Done!
