### ISSUE TITLE
[feat]: ice modifier `cmake` to build CMake projects 

### ISSUE THREAD

**Issue by vladdoster** [zdharma-continuum/zinit#294]
### If the feature request is for a plugin or theme, specify it here.

N/A

### If the feature solves a problem you have, specify it here.

Many projects use CMake (e.g., Neovim) and would be nice if Zinit could abstract the build process behind the ice `cmake''`. 

### Describe the proposed feature.

Add support for CMake that is exposed via the `cmake''` ice modifier.

### Describe alternatives you've considered

N/A

### Additional context

Zinit already supports Make so it makes sense to also support CMake.

### Related Issues

N/A

**Comment by psprint** [comment]
I think that the configure ice could be made abstract and call `cmake` when there's `CMakeLists.txt`.

**Comment by vladdoster** [comment]
Added in #351
