### ISSUE TITLE
[bug]: curl: option --tcp-fastopen: is unknown

### ISSUE THREAD

**Issue by raivivek** [zdharma-continuum/zinit#298]
### Describe the bug

Using `zinit` to setup a few plugins on a remote machine where the installed `curl` version does not support this flag. Is it possible to specify a different downloader through an environment variable or otherwise?

```
Setting up snippet: OMZ::plugins/bedtools
Downloading `OMZ::plugins/bedtools` (with curl, wget, lftp)…
curl: option --tcp-fastopen: is unknowncurl: try 'curl --help' or 'curl --manual' for more information
ERROR: Download failed.
```

```
❯ /bin/curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp

Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

### Steps to reproduce

1. Enable any plugin
2. Use a version of `curl` that does not support `--tcp-fastopen`
3. Plugin download fails

### Expected behavior

Plugin is installed successfully. 

### Operating System & Version

linux-gnu | pc | x86_64 | x86_64 | x86_64 x86_64

### Zsh version

zsh 5.8.1 (x86_64-pc-linux-gnu)

### Terminal emulator

xterm-kitty

**Comment by vladdoster** [comment]
Okay, I'll revert this change. The option sped up downloads. Sorry about this.

**Comment by vladdoster** [comment]
@raivivek Merged fix! Thanks again for reporting the issue :)!

**Comment by raivivek** [comment]
Thanks! This works for me. Although if it was a truly useful feature to have, perhaps one could detect if the flag is supported and only then use it. Maybe another ice that allows one to change download tool would work too. Just some thoughts! Thanks again!
