### ISSUE TITLE
`zinit pack'5.8' for zsh` is broken

### ISSUE THREAD

**Issue by vladdoster** [zdharma-continuum/zinit#3]
**Describe the bug**

The command `zinit pack'5.8' for zsh` is broken, but I'm not quite sure why. 

**To Reproduce**

```sh
zinit pack'5.8' for zsh
```

**Expected behavior**

Following command would build `zsh 5.8`:

```sh
zinit pack'5.8' for zsh
```

**Comment by alichtman** [comment]
Can you provide the error output?

**Comment by pschmitt** [comment]
That's probably because the zinit-zsh org has been deleted.

**Comment by pschmitt** [comment]
For what it is worth I've created https://github.com/pschmitt/zsh-packages-zsh which holds the latest code from Zsh-Packages/zsh

Source: https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/Zsh-Packages/zsh

@alichtman if you could add this repo to zhdarma-continuum then the fix would be quite trivial to implement.

```
 URL=https://raw.githubusercontent.com/zdharma-continuuum/$2/main/package.json 
```
