### ISSUE TITLE
[bug]: error: unknown option `show-current` when using `git` dependent zinit commands

### ISSUE THREAD

**Issue by raivivek** [zdharma-continuum/zinit#303]
### Describe the bug

I feel this might be related to a `git` version issue, but when I use a `zinit` command like `zinit self-update`, I see the following error. Apologies if `zinit` requires a min git version that I did not check carefully.

```
> zinit self-update
error: unknown option `show-current'
usage: git branch [options] [-r | -a] [--merged | --no-merged]
   or: git branch [options] [-l] [-f] <branchname> [<start-point>]
   or: git branch [options] [-r] (-d | -D) <branchname>...
   or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

[...]
```
The git used is the one installed by default on the remote machine.

```
> git --version
git version 1.8.3.1
```

### Steps to reproduce

1. Use the git version below with latest zinit
2. Run `zinit self-update`
3. Error message is shown

### Expected behavior

1. No error is shown

### Operating System & Version

linux-gnu | pc | x86_64 | x86_64 | x86_64 x86_64

### Zsh version

zsh 5.8.1 (x86_64-pc-linux-gnu)

### Terminal emulator

xterm-kitty

**Comment by vladdoster** [comment]
You would be correct in thinking it is the git version. 

`v.1.8.x` is what I'd expect to see on a CentOS 7 (e.g., somewhat ancient) system.

**Comment by vladdoster** [comment]
You might try this ;)

```zsh
 zi lucid make'PREFIX=$PWD PROFILE=BUILD install' nocompile for \                          
   atclone'autoconf; ./configure --prefix=$PWD; make PREFIX=$PWD' \                                              
   atpull'%atclone' \                                                 
   lbin'!**/bin/git' \                                                
  @git/git
```

**Comment by vladdoster** [comment]
<img width="628" alt="Screen Shot 2022-06-04 at 11 51 08" src="https://user-images.githubusercontent.com/10052309/172017234-62a5a19e-ee47-4cff-9515-93522765ba2b.png">

**Comment by raivivek** [comment]
Thanks! I appreciate the perspective. It's not a huge problem for me, so feel free to resolve the issue as you see fit. Cheers!

**Comment by vladdoster** [comment]
@raivivek 

tada 🎉 

## before

<img width="957" alt="Screen Shot 2022-06-10 at 18 41 47" src="https://user-images.githubusercontent.com/10052309/173167057-01228146-b166-4ca4-afad-01dc9446ffdd.png">

## after

<img width="864" alt="Screen Shot 2022-06-10 at 20 15 44" src="https://user-images.githubusercontent.com/10052309/173167078-70633343-cc97-49cd-91bd-2e0e32f0f3b1.png">

**Comment by vladdoster** [comment]
will be merged shortly :-)

**Comment by vladdoster** [comment]
@raivivek See #307 

Feedback welcome

**Comment by vladdoster** [comment]
@raivivek -- Merged. Please open a new issue if the issue persists.

Thanks again for taking the time to report the issue :^) !

**Comment by raivivek** [comment]
Great, thanks! Appreciate the quick resolution and all the effort. Cheers!
