### ISSUE TITLE
Fork request

### ISSUE THREAD

**Issue by psprint** [zdharma-continuum/zinit#317]
I.'ve created a zinit annex that allows to automatically extract any zinit command that loads a snippet or plugin from any web site.  I thought that it could be forked by continuum organization so that it would be broader available? What do you say?  It's at my account, @psprint.

**Comment by vladdoster** [comment]
I was going to ask the same thing in an issue in the repository. I think it makes sense.

**Comment by vladdoster** [comment]
Forked repository


https://github.com/zdharma-continuum/zinit-annex-pull
