### ISSUE TITLE
[bug]: Binary downloads directory and wrong readme instructions

### ISSUE THREAD

**Issue by avently** [zdharma-continuum/zinit#338]
### Describe the bug

Readme gives an example of how to download a binary:
https://github.com/zdharma-continuum/zinit#more-examples

```bash
zinit ice from"gh-r" as"program"
zinit light junegunn/fzf
```

The binary is downloaded, but not symlinked to any bin directory: nor `~/.local/bin`, nor `$ZPFX` (`~/.local/share/zinit/polaris/bin`),
The path is only added to `$PATH`. Is that expected or something is wrong? How to make symlinks from multiple programs to one directory without adding everything to $PATH (I will add only this directory to $PATH myself instead of tens other directories)?

Same readme mentiones another part of code here: https://github.com/zdharma-continuum/zinit#extending-git
```bash
zinit as"null" wait"1" lucid for \
    sbin    Fakerr/git-recall
```

Result:
```bash
Downloading sbin… (at label: sbin…)
remote: Not Found
fatal: repository 'https://github.com/sbin/' not found

Clone failed (code: 128).

Downloading Fakerr/git-recall…
⠴ ██████░░░░░ OBJ: 381, PACK: 381/381
~:
Downloading sbin… (at label: sbin…)
remote: Not Found
fatal: repository 'https://github.com/sbin/' not found

Clone failed (code: 128).
```

There are else some example of using the command here: https://github.com/zdharma-continuum/zinit-configs/blob/master/vladdoster/zshrc#L89

Added to .zshrc:
```bash
zi from'gh-r' lbin'!' nocompile for \
  lbin'!* -> jq'     @stedolan/jq
```

```
command not found: zi
```

```bash
zinit as"program" wait"2" lucid from'gh-r' lbin'!' nocompile for \
  lbin'!* -> jq'     @stedolan/jq
```

```
ERROR: Unknown subcommand: `lbin!` (it should be one of, e.g.: `load`, `snippet`, `update`, `delete`, …, e.g.: `zinit load username/reponame`) or a for-based command body (i.e.: e.g.: `zinit …ice-spec
… for …(plugin or snippet) ID-1 ID-2 ⋯⋯…`). See `help` for a more detailed usage information and the list of the subcommands.
```

I tried this:
```bash
zinit  from"gh-r" for \
        sbin"fzf" junegunn/fzf-bin
```
It downloaded a binary but then every time I open a shell I see:
```bash
Downloading sbinfzf… (at label: sbinfzf…)
gh-r: failed to find the correct GitHub release asset to download
```

### Steps to reproduce

See above

### Expected behavior

I expect to run a command and to get a binary, after that this binary have to be linked to, for example, $ZPFX or ~/.local/bin, And a correct readme, of couse. Lost some hours trying to find a working solution and didn't find any yet

### Operating System & Version

linux-gnu | pc | x86_64 | x86_64 | x86_64 unknown

### Zsh version

zsh 5.9 (x86_64-pc-linux-gnu)

### Terminal emulator

kitty

**Comment by vladdoster** [comment]
> Same readme mentiones another part of code here: [zdharma-continuum/zinit#extending-git](https://github.com/zdharma-continuum/zinit#extending-git)
>
> ```zsh
> zinit as"null" wait"1" lucid for \
>    sbin    Fakerr/git-recall
>```

This is a formatting error. The actual recipe works as intended.

```zsh
zinit as"null" wait"1" lucid for sbin Fakerr/git-recall
```

<img width="1052" alt="Screenshot 2022-07-10 at 4 31 59 AM" src="https://user-images.githubusercontent.com/10052309/178139262-9d1021a5-5761-4b26-a52c-e902df645193.png">

**Comment by avently** [comment]
That's strange, because this is what I see. Just copy-pasted your line:
![screenshot-2022-07-10_125103_070577539](https://user-images.githubusercontent.com/7953703/178139855-48ba06bd-1938-459c-b96e-bb58f5a293d6.png)

**Comment by vladdoster** [comment]
Is the `bin-gem-node` annex installed?

**Comment by avently** [comment]
Ah, nice catch!

So, I thought this is all built-in functions with bin, sbin, lbin but I couldn't find them in sources. I read about annex plugins and things more transparent now.
Basically, https://github.com/zdharma-continuum/zinit-annex-binary-symlink is what I was looking for in this issue: lbin like in your zshrc.  

Thanks, Vlad, for your help.
