### ISSUE TITLE
[bug]: _autocomplete.command:local:2: bad option: -P

### ISSUE THREAD

**Issue by tbenthompson** [zdharma-continuum/zinit#364]
### What happened?

I type a partial command and hit tab. Autocomplete works but I get the error message: `_autocomplete.command:local:2: bad option: -P`

For example:
```
tbent@caboose ~ % gre
_autocomplete.command:local:2: bad option: -P
tbent@caboose ~ % gre
gregorio  grep
```

Thanks so much for any help!!

### Steps to reproduce

I'm getting the error even with a minimal `.zshrc` like:
```
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
autoload -Uz compinit && compinit
```

### Operating System & Version

OS: darwin21.0 | Vendor: apple | Machine: x86_64 | CPU: arm64 | Processor: arm | Hardware: arm64

### Zsh version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Terminal emulator

xterm-kitty

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
@tbenthompson Are you using Brew?

**Comment by tbenthompson** [comment]
zsh is installed through brew, but not zinit. Is that a potential problem?

**Comment by tbenthompson** [comment]
Hmm, I like your theory but it doesn't seem to be holding up to the evidence:
1. I followed your instructions. (btw, does it matter the order of `bashcompinit` and `compinit` in `~/.zshrc`? I tried both orderings.)
2. I'm still getting the error. 

The error seems to occur for *any* completion that involves an executable. For example, as you can see in the screenshot:
- the filepath completion of `active` does not trigger any errors.
- the executable completion of `spotify` *does* trigger an error. But, the completion still succeeds.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/4241811/188023570-7231fad2-e07c-4731-bd81-f051c1ddd0f4.png">

**Comment by tbenthompson** [comment]
Ah, I think I solved the problem. I had `autoload -Uz compinit && compinit` after loading `zinit`. I've moved `autoload -Uz compinit && compinit` to the beginning of my `~/.zshrc` and everything works fine. I guess this is user error!
