### ISSUE TITLE
[bug]: gh-r linux wrong arch binary

### ISSUE THREAD

**Issue by q-b** [zdharma-continuum/zinit#374]
### What happened?

Zinit tries to download the wrong arch version on my system.
Shoud be x86_64 (ubuntu 20.04, nothing fancy) but instead it downloads ARM 32 versions.
I have seen reports for similar problems but with different OS and Arch (mac loading linux binaries instead of darwin etc.)

### Steps to reproduce

Note: `bat` is just an example, it happens with other repositories.

```
zi delete sharkdp/bat
```

```
# from .zshrc
zinit ice silent wait as"program" from"gh-r" pick"bat/bat" mv"bat* -> bat"
zinit light sharkdp/bat
```

```
Downloading sharkdp/bat…
(Requesting `bat-v0.22.1-arm-unknown-linux-musleabihf.tar.gz'…)
######################################################################## 100,0%                                
ziextract: Unpacking the files from: `bat-v0.22.1-arm-unknown-linux-musleabihf.tar.gz'…
ziextract: Successfully extracted and assigned +x chmod to the file: `bat-v0.22.1-arm-unknown-linux-musleabihf/bat'.
renamed 'bat-v0.22.1-arm-unknown-linux-musleabihf' -> 'bat'
```

### Operating System & Version

OS: linux-gnu | Vendor: ubuntu | Machine: x86_64 | CPU: x86_64 | Processor: x86_64 | Hardware: x86_64

### Zsh version

zsh 5.8 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

xterm-256color (Tilix)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by numToStr** [comment]
I am also having the same issue https://github.com/zdharma-continuum/zinit/pull/373#issuecomment-1246212326

**Comment by numToStr** [comment]
It seems zinit is now downloading correct binaries.

**Comment by seagle0128** [comment]
Still happen in the latest version. On x86_64, still download aarch64 binary.

```
zinit ice wait lucid as"null" from"gh-r" sbin
zinit light extrawurst/gitui
```

**Comment by vladdoster** [comment]
> Still happen in the latest version. On x86_64 (WSL2), download aarch64 binary.
> 
> 
> 
> ```shell
> 
> zinit ice wait lucid as"null" from"gh-r" sbin
> 
> zinit light extrawurst/gitui
> 
> ```

@seagle0128,

Please refrain from commenting on closed issues. Open a new issue with relevant details.
