### ISSUE TITLE
[bug]: egrep is deprecated

### ISSUE THREAD

**Issue by cdemoulins** [zdharma-continuum/zinit#375]
### What happened?

Update of plugin code use egrep command and since GNU grep 3.8, the command is deprecated and generate a warning.

https://www.phoronix.com/news/GNU-Grep-3.8-Stop-egrep-fgrep

### Steps to reproduce

zinit update --all

### Relevant output

```shell
Updating aperezdc/zsh-fzy
egrep: warning: egrep is obsolescent; using grep -E
Depuis https://github.com/aperezdc/zsh-fzy
Déjà à jour.
```

### Operating System & Version

OS: linux-gnu | Vendor: pc | Machine: x86_64 | CPU: x86_64 | Processor: unknown | Hardware: x86_64

### Zsh version

zsh 5.9 (x86_64-pc-linux-gnu)

### Terminal emulator

xterm-kitty (with tmux)

### Additional context

❯ grep --version
grep (GNU grep) 3.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
@cdemoulins Can you confirm #372 fixed this?

**Comment by cdemoulins** [comment]
Yes thanks !
