### ISSUE TITLE
[feat]: fork request

### ISSUE THREAD

**Issue by psprint** [zdharma-continuum/zinit#383]
### If the feature request is for a plugin or theme, specify it here.

zservices/make-server

### If the feature solves a problem you have, specify it here.

The server makes builds quicker – when one switches to the terminal to run `make`, a tail (from 1 line) of already running `make` will be shown, or a cat of previous, already finished `make` run.

### Describe the proposed feature.

The `zmake` command (aliased to `make` if `$MSERV_SETUP_ALIAS` is set) nicely interfaces with the background service – it'll run a custom target (e.g.: `install`) in foreground, with sync with the background `make` (which can be also customized to use specific options, via `$MSERV_ARGS`), so there are no drawbacks of running a background `make`.

The plugin is a service and nicely works with Zinit `service''` support – only a single instance of the `make-server` command is automatically managed to be run.

### Describe alternatives you've considered

There are no such low-complexity tools, except maybe for `CI` tools. One person reacted describing the `make-server` as a "tool with goals of CI".

**Comment by vladdoster** [comment]
See [zdharma-continuum/make-server](https://github.com/zdharma-continuum/make-server)
