### ISSUE TITLE
[bug]: failed to find the correct GitHub release asset to download, modify bpick-ICE 

### ISSUE THREAD

**Issue by amanjitsk** [zdharma-continuum/zinit#385]
### What happened?

The `bpick-ICE` does not work for the `neovim/neovim` repo with the github releases. This used to work before, but it just stopped working recently. And the `nvim.appimage` asset is indeed present
in the latest version on neovim [here](https://github.com/neovim/neovim/releases/tag/v0.7.2)

### Steps to reproduce

1. Enable plugin `neovim` using 
```zsh
zinit ice wait lucid from"gh-r" ver"latest" bpick"nvim.appimage" \
  as"null" mv"nvim* -> $PREFIX/bin/nvim"
zinit light neovim/neovim
```

### Relevant output

```shell
Downloading neovim/neovim…
gh-r: failed to find the correct GitHub release asset to download, modify bpick-ICE (current bpick: nvim.appimage).
```

### Operating System & Version

OS: linux-gnu | Vendor: ubuntu | Machine: x86_64 | CPU: x86_64 | Processor: x86_64 | Hardware: x86_64

### Zsh version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

xterm-kitty

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
@amanjitsk did you see https://github.com/zdharma-continuum/zinit/issues/228?

**Comment by chalkygames123** [comment]
Although I'm not sure if it's relevant to this issue, today I noticed that `cli/cli` has not been getting updates for a while even though I run `zinit update` regularly, so I deleted it with `zinit delete cli/cli` and tried to reinstall it. However, the download fails if the `ver` ice, needed to avoid pre-releases, is present.

Originally, my setup was:

```shell
zinit wait lucid as'program' for \
	from'gh-r' ver'latest' pick'gh/bin/gh' mv'gh* -> gh' atclone'./gh/bin/gh completion --shell zsh > _gh' atpull'%atclone' \
		cli/cli \
```

And the download failed:

```
Downloading cli/cli…
gh-r: failed to find the correct GitHub release asset to download.
```

I tried removing the `ver` ice:

```shell
zinit wait lucid as'program' for \
	from'gh-r' pick'gh/bin/gh' mv'gh* -> gh' atclone'./gh/bin/gh completion --shell zsh > _gh' atpull'%atclone' \
		cli/cli \
```

Then it succeeded:

```
Downloading cli/cli…
(Requesting `gh_2.16.1_macOS_amd64.tar.gz'…)
######################################################################################################################################################### 100.0%
ziextract: Unpacking the files from: `gh_2.16.1_macOS_amd64.tar.gz'…
ziextract: Successfully extracted and assigned +x chmod to the file: `gh_2.16.1_macOS_amd64/bin/gh'.
gh_2.16.1_macOS_amd64 -> gh
Installed 0 completions. They are stored in the $INSTALLED_COMPS array.
Skipped installing 1 completions. They are stored in the $SKIPPED_COMPS array.
```

**Comment by amanjitsk** [comment]
> @amanjitsk did you see #228?

The `sbin` approach doesn't work for me as it does not download the right version (the latest stable version using `ver'latest'` does not work. Furthermore, I can't even find `nvim` on my path with this approach. On top of that, with this approach, I have some libraries missing with the following error:
![image](https://user-images.githubusercontent.com/12499495/193656813-ac87417e-23b1-4b40-bab9-8bcf03c40e94.png)

Here is what I used to do before:

```zsh
zinit ice wait lucid from"gh-r" ver"latest" bpick"nvim.appimage" \
   as"null" mv"nvim* -> $PREFIX/bin/nvim"
zinit light neovim/neovim
```

Would it not be possible to have this AppImage approach anymore?

**Comment by vladdoster** [comment]
> Although I'm not sure if it's relevant to this issue, today I noticed that `cli/cli` has not been getting updates for a while even though I run `zinit update` regularly, so I deleted it with `zinit delete cli/cli` and tried to reinstall it. However, the download fails if the `ver` ice, needed to avoid pre-releases, is present.
> 
> Originally, my setup was:
> 
> ```shell
> zinit wait lucid as'program' for \
> 	from'gh-r' ver'latest' pick'gh/bin/gh' mv'gh* -> gh' atclone'./gh/bin/gh completion --shell zsh > _gh' atpull'%atclone' \
> 		cli/cli \
> ```
> 
> And the download failed:
> 
> ```
> Downloading cli/cli…
> gh-r: failed to find the correct GitHub release asset to download.
> ```
> 
> I tried removing the `ver` ice:
> 
> ```shell
> zinit wait lucid as'program' for \
> 	from'gh-r' pick'gh/bin/gh' mv'gh* -> gh' atclone'./gh/bin/gh completion --shell zsh > _gh' atpull'%atclone' \
> 		cli/cli \
> ```
> 
> Then it succeeded:
> 
> ```
> Downloading cli/cli…
> (Requesting `gh_2.16.1_macOS_amd64.tar.gz'…)
> ######################################################################################################################################################### 100.0%
> ziextract: Unpacking the files from: `gh_2.16.1_macOS_amd64.tar.gz'…
> ziextract: Successfully extracted and assigned +x chmod to the file: `gh_2.16.1_macOS_amd64/bin/gh'.
> gh_2.16.1_macOS_amd64 -> gh
> Installed 0 completions. They are stored in the $INSTALLED_COMPS array.
> Skipped installing 1 completions. They are stored in the $SKIPPED_COMPS array.
> ```

`latest` isn't a version so it doesn't find anything. Version 2.16.1 is the latest version (see [cli releases](https://github.com/cli/cli/releases).

For example, to get v2.15.0 I'd use the following recipe:

```zsh
zi for \                                                                                             <<<
    as'program' \
    atclone'./gh/bin/gh completion --shell zsh > _gh' \
    atpull'%atclone' \
    from'gh-r' \
    mv'gh* -> gh' \
    pick'gh/bin/gh' \
    ver'v2.15.0' \
  cli/cli
```

Which results in:

```zsh
/usr/local/Cellar
ᐳ zi delete cli/cli --yes

Done (action executed, exit code: 0)

/usr/local/Cellar
ᐳ zi for \
    as'program' \
    atclone'./gh/bin/gh completion --shell zsh > _gh' \
    atpull'%atclone' \
    from'gh-r' \
    mv'gh* -> gh' \
    pick'gh/bin/gh' \
    ver'v2.15.0' \
  cli/cli

Downloading cli/cli…
(Requesting `gh_2.15.0_macOS_amd64.tar.gz'…)
#################################################################################################### 100.0%
ziextract: Unpacking the files from: `gh_2.15.0_macOS_amd64.tar.gz'…
ziextract: Successfully extracted and assigned +x chmod to the file: `gh_2.15.0_macOS_amd64/bin/gh'.
renamed 'gh_2.15.0_macOS_amd64' -> 'gh'
Installed 0 completions. They are stored in the $INSTALLED_COMPS array.
Skipped installing 1 completions. They are stored in the $SKIPPED_COMPS array.

/usr/local/Cellar 16s
ᐳ
```

**Comment by vladdoster** [comment]
> > @amanjitsk did you see #228?
> 
> The `sbin` approach doesn't work for me as it does not download the right version (the latest stable version using `ver'latest'` does not work. Furthermore, I can't even find `nvim` on my path with this approach. ~On top of that, with this approach, I have some libraries missing with the following error~ (this actually happens even with the appimage): ![image](https://user-images.githubusercontent.com/12499495/193656813-ac87417e-23b1-4b40-bab9-8bcf03c40e94.png)
> 
> Here is what I used to do before:
> 
> ```shell
> zinit ice wait lucid from"gh-r" ver"latest" bpick"nvim.appimage" \
>    as"null" mv"nvim* -> $PREFIX/bin/nvim"
> zinit light neovim/neovim
> ```
> 
> Would it not be possible to have this AppImage approach anymore?

The `GLIBC` version error is a dependency error. I discuss the cons of AppImages in the issue I linked ([comment link](https://github.com/zdharma-continuum/zinit/issues/228#issuecomment-1108823096)). AppImages aren't self contained. They depend on the glibc of the host at the very least. You'll be unable to run Neovim (appimage, binary, compiled, etc.) until you update glibc.

Zinit currently filters out AppImages and I have yet to come across a project that releases an AppImage but no binary. Do you have a specific reason for using the AppImage?

**Comment by amanjitsk** [comment]
Makes sense, thanks for that link (I went back and read it again).
The only issue is that with the recipe described above as
```zsh
zinit from'gh-r' sbin'**/nvim' ver'stable' for neovim/neovim
```
I can't even find `nvim` on my `PATH` after this, not sure if this was intended (apart from the dependency issue).
How can I do the same with the `sbin` approach (I thought that is what the `sbin` ice does)

**Comment by chalkygames123** [comment]
@vladdoster While the [documentation](https://github.com/zdharma-continuum/zinit#cloning-options) says the following, do you mean it's out of date?

> Used with `from"gh-r"` (i.e. downloading a binary release, e.g. for use with `as"program"`) – selects which version to download. Default is latest, can also be explicitly `ver"latest"`. Works also with regular plugins and packages (`pack` ice) checkouts e.g. `ver"abranch"`, i.e. a specific version. **Does not work with snippets.**<

I'm also not sure why pre-release is selected if explicit `ver'latest'` is not present. While I can't reproduce it as the latest version is stable right now, I haven't experienced the same problem with any other plugin.

**Comment by vladdoster** [comment]
> Makes sense, thanks for that link (I went back and read it again). The only issue is that with the recipe described above as
> 
> ```shell
> zinit from'gh-r' sbin'**/nvim' ver'stable' for neovim/neovim
> ```
> 
> I can't even find `nvim` on my `PATH` after this, not sure if this was intended (apart from the dependency issue). How can I do the same with the `sbin` approach (I thought that is what the `sbin` ice does)

---

Correct, you will not see it in $PATH. The whole purpose of `sbin` is to enable running programs and scripts without adding anything to $PATH.

Please see [bin-gem-node annex documentation](https://github.com/zdharma-continuum/zinit-annex-bin-gem-node#how-it-works--birds-eye-view).
