### ISSUE TITLE
Update the default install dir

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/zinit#40]
As of now the zinit installer defaults to installing stuff under `$HOME/.zinit/bin` - which is a bit weird (the bin part especially) and clutters the users `$HOME`.

A more sensible default would be `$XDG_DATA_HOME/zinit` (ie. `$HOME/.local/share/zinit`).

Related to #28

Tasks:
- [ ] update zinit installer to install to `XDG_DATA_HOME`
- [ ] update documentation
- [ ] update the migration wiki page

**Comment by alichtman** [comment]
There are some env vars you can tweak to add this behavior BUT we should have sensible defaults.
