### ISSUE TITLE
[feat]: fork request of zservices/command-CI-server

### ISSUE THREAD

**Issue by psprint** [zdharma-continuum/zinit#400]
### If the feature request is for a plugin or theme, specify it here.

zservices/command-CI-server

### If the feature solves a problem you have, specify it here.

I often run long, complex commands via history mechanism. I think that it's common to do so, e.g.: to execute a long e.g.: `./configure --prefix=… CFLAGS=…` command. In my opinion such reaching for past commands is too fragile, too irritating when e.g.: multiple `./configure …` commands are stored.

### Describe the proposed feature.

The `command-CI-server` is a utility that works like many CI solutions that allow to define actions to take via a YAML file. Here, there are INI files that each defines a command to run, with background `command-server` every defined interval or manually, via `cmd run {CMD-ID}` script. The command definition files are read from `~/.config/cmds` dir and from any dir set in `$CMD_COMMANDS_PATH`, like `~/cmds`, for example.

### Describe alternatives you've considered

I didn't see any CI-like tool in OpenSource software.

**Comment by vladdoster** [comment]
Closing in favor of `configure` & `make` ices (e.g., #458, #351, #346)

@psprint
