### ISSUE TITLE
sbin annex does not work with zsh 5.4.2

### ISSUE THREAD

**Issue by cgjosephlee** [zdharma-continuum/zinit#41]
**Describe the bug**

`sbin` did not create any shim in corresponding directory. But when I delete the package, zinit warns that
```
bin-gem-node annex: The fzf shim didn't exist in $ZPFX/bin (or isn't a regular file)
```

**Zinit config**
Steps to reproduce the behavior. Please include any relevant config section
that may help the maintainers reproduce the issue.

```
zinit light-mode for \
    zdharma-continuum/z-a-rust \
    zdharma-continuum/z-a-patch-dl \
    zdharma-continuum/z-a-as-monitor \
    zdharma-continuum/z-a-bin-gem-node

zinit wait lucid from"gh-r" as"null" for \
    sbin"fzf" @junegunn/fzf \
    sbin"**/fd" @sharkdp/fd \
    sbin"**/bat" @sharkdp/bat \
    sbin"**/exa" @ogham/exa
```

**Expected behavior**

**Screenshots (optional)**

**Versions:**
 - $ZSH_VERSION == 5.4.2
 - Operating system name and version (uname -a): ubuntu 18.04

**Additional context**

**Comment by pschmitt** [comment]
I can reproduce your issue with the following script:

```bash
#!/usr/bin/env bash

create_config() {
  local tempfile
  tempfile=$(mktemp)

  trap 'rm -f $tempfile' EXIT INT
cat << EOM > "$tempfile"
  zinit light-mode for \
      zdharma-continuum/z-a-rust \
      zdharma-continuum/z-a-patch-dl \
      zdharma-continuum/z-a-as-monitor \
      zdharma-continuum/z-a-bin-gem-node

  zinit wait lucid from"gh-r" as"null" for \
      sbin"fzf" @junegunn/fzf \
      sbin"**/fd" @sharkdp/fd \
      sbin"**/bat" @sharkdp/bat \
      sbin"**/exa" @ogham/exa
EOM
  echo "$tempfile"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
  INIT_CONFIG=$(create_config)

  docker run -it --rm -v "${INIT_CONFIG}:/init.zsh" ghcr.io/pschmitt/zinit:zsh-5.4.2-latest
fi
```

Will look into it.

**Comment by pschmitt** [comment]
For fzf you can at least use the zinit-package:

```zsh
zinit pack"binary+keys" for fzf
```

There are some issues with the bin-gem-node annex though, that's for sure.

**Comment by cgjosephlee** [comment]
Thank you for investigating this. For now I use `as"program"` ice and pretend that I cannot see my terrifying `$path`. lol

**Comment by pschmitt** [comment]
This issue seems only be happening with older zsh version.
Using the snippet above and setting the ZSH version to 5.5.1 (tag: `zsh-5.5.1`) the shims get created as expected.

**Comment by pschmitt** [comment]
```zsh
zinit pack"5.8" for zsh
```

😇

**Comment by cgjosephlee** [comment]
Okay... So it's a zsh version problem... I mostly work on remote server where I don't have root privilege. I think I can only give up on this fantastic feature for now. Thank you.

**Comment by pschmitt** [comment]
Imma close this for now, 

To reduce the number of dirs in your `PATH` you can also want to give z-a-linkbin a try:
https://github.com/NICHOLAS85/z-a-linkbin

**Comment by cgjosephlee** [comment]
It works! Tested with zsh-v5.4.2 from ubuntu 18.04 and zsh-v5.1.1 from ubuntu 16.04.
