### ISSUE TITLE
[bug]: zinit always generate zinit.1 to ~/.local/share/zinit/polaris/man/man1, even if $ZPFX is not ~/.local/share/zinit/polaris

### ISSUE THREAD

**Issue by Freed-Wu** [zdharma-continuum/zinit#413]
### What happened?

```zsh
ZPFX="$HOME/.local"
zinit id-as depth'1' null for zdharma-continuum/zinit
```

Expect `~/.local/man/man1/zinit.1`, however `~/.local/share/zinit/polaris/man/man1/zinit.1`

### Steps to reproduce

As above

### Operating System & Version

linux 6.02

### Zsh version

5.9

### Terminal emulator

wezterm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
I think you should set "$ZINIT[MAN_DIR]" defined [here](https://github.com/zdharma-continuum/zinit#customizing-paths).

**Comment by Freed-Wu** [comment]
Why not let `$ZINIT[MAN_DIR]` is `$ZPFX/share/man` by default?

**Comment by Freed-Wu** [comment]
I found I have two zinit.1, every time I delete them, next time they will be generated.

```
❯ ls ~/.local/man/man1 ~/.local/share/zinit/polaris/man/man1
/home/wzy/.local/man/man1:
 zinit.1

/home/wzy/.local/share/zinit/polaris/man/man1:
 zinit.1
```

**Comment by Freed-Wu** [comment]
```zsh
ZPFX="$HOME/.local"
ZINIT[MAN_DIR]=$ZPFX/share/man
zinit id-as depth'1' null for zdharma-continuum/zinit
```

It still generate `~/.local/share/zinit/polaris/man`

**Comment by Freed-Wu** [comment]
Oh, I must add `$ZPFX` before `source zinit`. Now it can work:
```sh
ZPFX="$HOME/.local"
typeset -A ZINIT
ZINIT[MAN_DIR]="$ZPFX/share/man"
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
if [[ -f $XDG_DATA_HOME/zinit/plugins/zinit/zinit.zsh ]]; then
  . $XDG_DATA_HOME/zinit/plugins/zinit/zinit.zsh
elif (($+commands[git])); then
  git clone --depth=1 https://github.com/zdharma-continuum/zinit \
    $XDG_DATA_HOME/zinit/plugins/zinit
  . $XDG_DATA_HOME/zinit/plugins/zinit/zinit.zsh
else
  return
fi
```
