### ISSUE TITLE
[bug]: incorrect binaries downloaded from gh-r on an ARM EC2

### ISSUE THREAD

**Issue by fredcallaway** [zdharma-continuum/zinit#431]
### What happened?

zinit is not grabbing the correct architecture from github releases on an ARM EC2 instance.

### Steps to reproduce

```
❯ echo $CPUTYPE
aarch64

❯ zinit from"gh-r" for sbin"fzf" @junegunn/fzf

Downloading junegunn/fzf…
(Requesting `fzf-0.35.1-linux_amd64.tar.gz'…)
```

### Operating System & Version

OS: linux-gnu | Vendor: unknown | Machine: aarch64 | CPU: arm64 | Processor: aarch64 | Hardware: aarch64

### Zsh version

zsh 5.8.1 (aarch64-unknown-linux-gnu)

### Terminal emulator

iTerm screen-256color

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
@fredcallaway, Thanks for reporting this bug! This is a gap in our unit tests currently due to no ARM option for Github action runners. 

Will get fixed ASAP.

**Comment by fredcallaway** [comment]
Checking in on this. Is there anything I could do to help?

**Comment by vladdoster** [comment]
@fredcallaway You can test the fix :^)

```zsh
git --work-tree=$ZINIT[BIN_DIR] fetch --all;
git --work-tree=$ZINIT[BIN_DIR] checkout refactor/zinit-install;
zi delete junegunn/fzf --yes;
zi as'null' from'gh-r' sbin for @junegunn/fzf;
```

<img width="1032" alt="Screenshot 2022-12-22 at 18 17 16" src="https://user-images.githubusercontent.com/10052309/209247025-efda61bd-5b23-4d1f-a04c-b6f8e9bf833f.png">

**Comment by fredcallaway** [comment]
Hmm... on my EC2, I seem to get a darwin_arm binary. (Also I had to replace --work-tree with -C)

<img width="719" alt="image" src="https://user-images.githubusercontent.com/7883156/209253555-a04950a4-8004-4544-8357-4ee47678675c.png">

```
❯ uname -a
Linux recserver.localdomain 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 17:01:09 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

❯ git -C $ZINIT[BIN_DIR] status
On branch refactor/zinit-install
Your branch is up to date with 'origin/refactor/zinit-install'.
```

Perhaps it has to do with the extra aarch64s in the uname output?

**Comment by fredcallaway** [comment]
A possible workaround to deal with parsing difficulties would be to have an optional environment variable specifying the architecture (which would be set in a machine-specific rc file).

**Comment by vladdoster** [comment]
@fredcallaway,

Sorry about that. I had pushed breaking changes. Could you try again?

**Comment by fredcallaway** [comment]
OK that did it! Many thanks for your work maintaining this wonderful project.

By the way, I found that I had to run zi/zinit in a new shell to get the updated version from the pull.
```
zsh -ic "zi as'null' from'gh-r' sbin for @junegunn/fzf;"
```

**Comment by vladdoster** [comment]
@fredcallaway I'm going to reopen this until the PR is merged.

**Comment by vladdoster** [comment]
<img width="1312" alt="Screenshot 2023-01-07 at 22 46 35" src="https://user-images.githubusercontent.com/10052309/211180845-e92c88ab-4fbb-4663-a501-8fcb9f90a1ca.png">
