### ISSUE TITLE
[bug]: PR #429 breaks plugins

### ISSUE THREAD

**Issue by tiancheng92** [zdharma-continuum/zinit#433]
### What happened?

Plugin functionality breaks, can not use 'wait'

### Steps to reproduce

N/A

### Operating System & Version

OS: darwin21.3.0 | Vendor: apple | Machine: arm | CPU: arm64 | Processor: arm | Hardware: arm64

### Zsh version

zsh 5.9 (arm-apple-darwin21.3.0)

### Terminal emulator

xterm-256color

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tiancheng92** [comment]
@psprint

**Comment by MarcAurel** [comment]
@tiancheng92 I had the same issue. The faulty commit just got reverted: https://github.com/zdharma-continuum/zinit/commit/cfd32618921ce0626a6deadc794da962750a845d

**Comment by vladdoster** [comment]
Fixed in #432
