### ISSUE TITLE
[doc]: Missing documentation for reinstalling/uninstalling zinit

### ISSUE THREAD

**Issue by okuramasafumi** [zdharma-continuum/zinit#446]
### Problem

I have some issue about zinit where I see messages like `compinit:527: no such file or directory: /Users/okuramasafumi/.local/share/zinit/completions/_autocomplete.all_matches`.
I'd like to cleanup my zinit environment by reinstalling it, but could not find a documentation describing reinstall method.
Also, if I want to switch to some other alternatives, uninstalling documentation would help.

### Suggested improvement

Adding uninstalling documentation should be good. I believe we can reinstall zinit simply by uninstalling it and installing it again.

**Comment by vladdoster** [comment]
@okuramasafumi Great suggestion. 

A few things that you can immediately use:


1. Did you see the [completions section](https://github.com/zdharma-continuum/zinit#completions-1) in README.md?

2. Missing completions

Error:

```zsh
compinit:527: no such file or directory: /Users/okuramasafumi/.local/share/zinit/completions/_autocomplete.all_matches
```

Fix:

```zsh
cclear
```

---

I've been meaning to add a `re-install` command. I will open an issue to track the progress.

**Comment by alichtman** [comment]
Just for clarity, the command you run in your terminal is `$ zinit cclear`

**Comment by okuramasafumi** [comment]
Thank you, I run `zinit cclear` command and it seems some completions were removed. I'll see if it resolves my issue.
