### ISSUE TITLE
[maint]: a new gh-r test

### ISSUE THREAD

**Issue by psprint** [zdharma-continuum/zinit#449]
### Summary

I saw that there is a group of gh-r tests that download multiple projects. There is one other somewhat interesting project to test: naggie/dstask, because zinit normally chooses wrong "import" binary, however with a  clever `bpick''` this can be fixed:

```zsh
zi sbin'dstask*->tsk' bpick'^*import*' ghapi from'gh-r' for dstas
```

The `bpick''` iced blocks "import" binaries and makes zinit choose the main binary,  because `^` is a negation.

**Comment by vladdoster** [comment]
@psprint What does `ghapi` do?

**Comment by psprint** [comment]
@vladdoster: ah, I've forgot to clear unscope annex. 

```
zi  from'gh-r' sbin'dstask*->tsk' bpick'^*import*' for naggie/dstask
```

**Comment by vladdoster** [comment]
@psprint PR open #455

**Comment by vladdoster** [comment]
<img width="627" alt="Screenshot 2023-01-08 at 15 31 20" src="https://user-images.githubusercontent.com/10052309/211220132-d04a8766-ae5b-4955-b8ec-f28dc009c18b.png">
