### ISSUE TITLE
💡 Proposal: Update the name of the "master" branch to main

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/zinit#46]
As the title states. The default is king and main is the new master.

TODOs:
- [x] Update the `zinit self-update` subcommand so that is switches automagically to the new branch
- [x] Update the installation doc to fetch the `install.sh` from the main branch, instead of master

**Comment by alichtman** [comment]
Happy to sign off on this.

**Comment by pschmitt** [comment]
Ran a few test to see what happens to all the `githubusercontent.com` URLs when you rename a branch via the GitHub UI.

Their web servers redirect from `/master/xyz`to `/main/xyz`, which is nice.

**Comment by pschmitt** [comment]
Fixed by #100
