### ISSUE TITLE
[bug]: shift count must be <= $#

### ISSUE THREAD

**Issue by king-11** [zdharma-continuum/zinit#463]
### What happened?

on shell start i get a lot of such errors 

```zsh
compinit:527: no such file or directory: /home/king-11/.local/share/zinit/completions/_android
compinit:527: no such file or directory: /home/king-11/.local/share/zinit/completions/_archlinux-java
compinit:527: no such file or directory: /home/king-11/.local/share/zinit/completions/_artisan
compinit:527: no such file or directory: /home/king-11/.local/share/zinit/completions/_atach
compinit:shift:529: shift count must be <= $#
compinit:527: no such file or directory: /home/king-11/.local/share/zinit/completions/_bitcoin-cli
...
```

### Steps to reproduce

Start the shell with latest zinit version in fedora linux

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/52061363/212491650-ca00dcb5-9f8d-469f-8a89-c1adaeb6702b.png)

### Operating System & Version

OS: linux-gnu | Vendor: redhat | Machine: x86_64 | CPU: x86_64 | Processor: x86_64 | Hardware: x86_64

### Zsh version

zsh 5.9 (x86_64-redhat-linux-gnu)

### Terminal emulator

xterm-256color

### If using WSL on Windows, which version of WSL

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
@king-11,

A few questions:

1. Did you recently change something in your config?
2. What is the output of the following command:
```zsh
zinit version
```

**Comment by crai0** [comment]
@king-11 I was able to remove the dangling completions using `zinit cclear` which fixed the errors

**Comment by vladdoster** [comment]
@crai0, 

This issue should not happen anymore due to a recent patch.

**Comment by psprint** [comment]
Remember: `zinit cclear` any time there are such errors

sob., 15 kwi 2023, 20:09 użytkownik vladislav doster <
***@***.***> napisał:

**Comment by king-11** [comment]
Thanks @crai0 @psprint this did for me I ran both

```
zinit cclear
zinit creinstall zsh-users/zsh-completions
```

**Comment by vladdoster** [comment]
Locking issue due to reported issue has been resolved.

Open a new issue and reference this issue if the problem persists.
