### ISSUE TITLE
[feat]: To support SVN after Github pulls the plug on it

### ISSUE THREAD

**Issue by ngocphamm** [zdharma-continuum/zinit#465]
### If the feature solves a problem you have, specify it here.

I'm using a few plugins from Prezto, so I have to use it as SVN snippets.

```
zinit svn for \
  PZT::modules/environment \
  PZT::modules/helper \
  PZT::modules/git \
  PZT::modules/editor
```

However, Github just announced they will stop supporting it next year https://github.blog/2023-01-20-sunsetting-subversion-support/

I'm wondering if there's a better way to get those Prezto plugins/scripts work with Zinit without SVN, and if not, is there a way to support a similar approach for getting those with Zinit.

### Describe the proposed feature.

I don't really have one. Sorry.

**Comment by HeroCC** [comment]
Looks like the [sun has set](https://github.blog/changelog/2024-01-08-subversion-has-been-sunset/):
```
Setting up snippet: OMZP::brew
Downloading `OMZP::brew` (with Subversion)…
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ohmyzsh/ohmyzsh/trunk/plugins/brew'
svn: E900002: Subversion support temporarily disabled.

GitHub has temporarily disabled Subversion support as part of a planned brownout
in order to give you advance notice of the upcoming permanent removal of
Subversion support on 2024-01-08.

Please see https://github.blog/2023-01-20-sunsetting-subversion-support/ for details.
```

**Comment by cawaltrip** [comment]
We should close this in favor of tracking in #504.
