### ISSUE TITLE
Can't install OMZ plugin that has multiple files (Subversion not found)

### ISSUE THREAD

**Issue by GaryBoone** [zdharma-continuum/zinit#481]
### What happened?

I'm unable to figure out how to load an OMZ plugin that has more than one file. In particular, [aliases](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aliases) is implemented in Python, so `cheatsheet.py` from the same directory must also be downloaded.

From the [wiki](https://zdharma-continuum.github.io/zinit/wiki/INTRODUCTION/), "Snippets are single files..." and "Moreover, snippets support Subversion protocol, supported also by Github. This allows to load snippets that are multi-file..." Here is the example given there:

```
# URL points to directory
zinit ice svn
zinit snippet PZT::modules/docker
```

### Steps to reproduce

However, when I add to my `.zshrc`:

```
# URL points to directory
zinit ice svn
zinit snippet OMZP::aliases
```

### Relevant output

```shell
The error is:

Setting up snippet: OMZP::aliases
Downloading `OMZP::aliases` (with Subversion)…
Warning: Subversion not found , please install it to use `svn' ice.
.zinit-mirror-using-svn:27: command not found: svn
```
```


### Screenshots and recordings

_No response_

### Operating System & Version

OS: darwin22.1.0 | Vendor: apple | Machine: x86_64 | CPU: x86_64 | Processor: i386 | Hardware: x86_64

### Zsh version

zsh 5.9 (x86_64-apple-darwin22.1.0)

### Terminal emulator

xterm-256color

### If using WSL on Windows, which version of WSL

None

### Additional context

Additional question: What should be the incantation to turboload `OMZP::aliases`?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dnanhkhoa** [comment]
It looks like `svn` hasn't been installed yet. If you are using macOS, you can install svn using homebrew. Using `brew install svn` to install it first.

**Comment by GaryBoone** [comment]
While that makes sense, none of the zinit documentation that I've found has said that svn needs to be installed. Seems strange to need another protocol other than Git to download from Github. My reading was that zinit used the svn protocol, which GitHub supports, not that svn was required.

I just noticed this comment on the [wiki](https://github.com/zdharma-continuum/zinit#use-zi-ice-svn-if-a-pluginsnippet-requires-an-entire-subdirectory) under `Cloning Options`/`svn`: "Does not work with plugins." So maybe this is a known issue.

Maybe this bug should be changed to be "Support multiple file downloads with Git".

**Comment by vladdoster** [comment]
@GaryBoone,

> While that makes sense, none of the zinit documentation I've found has said that svn needs to be installed.
I agree the documentation needs some updating and elaboration of certain features.


> Warning: Subversion not found, please install it to use `svn' ice.

However, I will point out that the error message states you need to install Subversion.

> Seems strange to need another protocol other than Git to download from Github. My reading was that zinit used the svn protocol, which GitHub supports, not that svn was required.

`git-svn` is a ~2000 line Perl script using the `SVN:Core` CPAN module.  

You're _technically_ correct Git supports SVN, but it isn't quite that cut and dry.

The `git-svn` subcommand is implemented as a perl script, see [here](https://github.com/git/git/blob/9d530dc0024503ab4218fe6c4395b8a0aa245478/git-svn.perl). The script expects that the package `SVN::Core` is installed otherwise exits. And on the SVN::Core CPAN (perl package manager) page has the following message:

> If you are looking for SVN::Core, it gets built with the Subversion binaries on your system, and is not available on CPAN.
> You need to specify at configure time if it should be built and installed. If your OS app packaging didn't do that for you then check

So to to run `git-svn` you need Subversion installed.

**Comment by vladdoster** [comment]
@GaryBoone,

Closing issue in favor of #504 for tracking progress on removing the Subversion dependency.
