### ISSUE TITLE
[bug]: can not run zinit update

### ISSUE THREAD

**Issue by tiancheng92** [zdharma-continuum/zinit#502]
### What happened?

can not run zinit update
![Xnip2023-04-15_09-04-53](https://user-images.githubusercontent.com/42594679/232175556-3f05d2a0-3e08-44af-8ce2-9dfe11ef3703.jpg)

### Steps to reproduce

```bash
zi update -a ; echo $?
1

➜ zi update ; echo $?
1

➜ zi ls ; echo $?
ERROR: Unknown subcommand: `ls` (it should be one of, e.g.: `load`, `snippet`, `update`, `delete`, …, e.g.: `zinit load username/reponame`) or a for-based command body (i.e.: e.g.: `zinit …ice-spec… for …(plugin or snippet) ID-1 ID-2 ⋯⋯…`). See `help` for a more detailed usage information and the list of the subcommands.
1

➜ zi list-plugins ; echo $?
ERROR: Unknown subcommand: `list-plugins` (it should be one of, e.g.: `load`, `snippet`, `update`, `delete`, …, e.g.: `zinit load username/reponame`) or a for-based command body (i.e.: e.g.: `zinit …ice-spec… for …(plugin or snippet) ID-1 ID-2 ⋯⋯…`). See `help` for a more detailed usage information and the list of the subcommands.
1

➜ zi version
zinit v3.10.0-9-g034e265e (darwin22.1.0_arm64)
```

### Operating System & Version

OS: darwin22.1.0 | Vendor: apple | Machine: arm | CPU: arm64 | Processor: arm | Hardware: arm64

### Zsh version

zsh 5.9 (arm-apple-darwin22.1.0)

### Terminal emulator

xterm-256color

### If using WSL on Windows, which version of WSL

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
I just noticed this as well. Working on fix now.

The fix will be a refactor to decouple the `update` and `status` commands. 

Another bug (of many) related to the commands:

```zsh
zinit status
```

Attempts to update Zinit.

**Comment by vladdoster** [comment]
@tiancheng92,

I have `update` and `status` subcommands working on branch `fix/zinit-update-and-status`

If you have time, please try it out.

```zsh
cd $ZINIT[BIN_DIR]
git pull origin;
git checkout origin fix/zinit-update-and-status
cd -
exec zsh -il
```

**Comment by tiancheng92** [comment]
I tried it, and as you said, the update function is back. @vladdoster

**Comment by 0x7a7a** [comment]
> @tiancheng92,
> 
> I have `update` and `status` subcommands working on branch `fix/zinit-update-and-status`. Please note, most flags (`--all`) work, but others (`--urge`, `--reset`) do not.
> 
> However, it does add the ability to update or get the status of multiple packages at once, whereas before it was just all or one.
> 
> If you have time, please try it out.
> 
> ```shell
> cd $ZINIT[BIN_DIR]
> git pull --all
> git checkout fix/zinit-update-and-status
> cd -
> exec zsh -il
> ```

I also met the same problem, and I solved it according to your instructions,thanks.
What I want to ask is, will I be in this branch in the future?

**Comment by 0x7a7a** [comment]
I seem to have a new problem.
![image](https://user-images.githubusercontent.com/8832748/232432250-2e9e2e55-7b72-4022-b8ab-c1fe1e186453.png)

**Comment by vladdoster** [comment]
> I seem to have a new problem.
> 
> ![image](https://user-images.githubusercontent.com/8832748/232432250-2e9e2e55-7b72-4022-b8ab-c1fe1e186453.png)
> 
> 

@0x7a7a, 

If still an issue, open a new issue.

**Comment by 0x7a7a** [comment]
> > I seem to have a new problem.
> > ![image](https://user-images.githubusercontent.com/8832748/232432250-2e9e2e55-7b72-4022-b8ab-c1fe1e186453.png)
> 
> @0x7a7a,
> 
> If still an issue, open a new issue.

No more questions now, thanks for your work and reply
