### ISSUE TITLE
[bug]: Cannot download AppImages from gh-r?

### ISSUE THREAD

**Issue by psprint** [zdharma-continuum/zinit#519]
### What happened?

I've tried to download an AppImage from GitHub Releases:

```zsh
zi id-as'NC' from"gh-r" bpick"*" sbin"*.AppImage -> NC" for psprint/n-commodore 
```

and error occurred:

![appimage-rep](https://user-images.githubusercontent.com/6049288/236958149-7f357ef4-7dea-4562-95b1-152c4e7abb98.png)

### Steps to reproduce

1. Run `zi from"gh-r" bpick"*.AppImage"` on any GH-Releases project shipping AppImages 
2. See the error.

### Operating System & Version

 OS: linux-gnu | Vendor: pc | Machine: x86_64 | CPU: x86_64 | Processor: x86_64 | Hardware: x86_64

### Zsh version

zsh 5.8 (x86_64-mandriva-linux-gnu)

### Terminal emulator

xterm

### If using WSL on Windows, which version of WSL

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
Discussion about the reason for removing in [issue 228](https://github.com/zdharma-continuum/zinit/issues/228).
