### ISSUE TITLE
[bug]: gh-r linux wrong arch binary -- downloads aarch64 instead of x86_64

### ISSUE THREAD

**Issue by mojolo** [zdharma-continuum/zinit#539]
### What happened?

On my x86_64 system running **Kubuntu 23.04**, `znit` `gh-r` downloads the wrong arch version for [navi](https://github.com/denisidoro/navi). It downloads `navi-v2.22.1-aarch64-unknown-linux-gnu.tar.gz` instead of `navi-v2.22.1-x86_64-unknown-linux-musl.tar.gz`.

Similar bug report: #374 

### Steps to reproduce

I'm using the `binary-symlink` annex to load [navi](https://github.com/denisidoro/navi). It downloads the correct arch for all the other bins I load. Here's the snippet from my `.zshrc`:

```
zi lucid from"gh-r" lbin'!' nocompile atpull'%atclone' for \
    pemistahl/grex \
    denisidoro/navi \
  atclone'mkdir -p $ZPFX/{bin,man/man1} ;
      cp -vf fd*/fd.1 $ZINIT[MAN_DIR]/man1/' \
    @sharkdp/fd \
  atclone'mkdir -p $ZPFX/{bin,man/man1} ;
      cp -vf lsd*/lsd.1 $ZINIT[MAN_DIR]/man1/' \
    lsd-rs/lsd \
  atclone'mkdir -p $ZPFX/{bin,man/man1,man/man5} ;
      cp -vf completions/exa.zsh completions/_exa ;
      cp -vf man/exa.1 $ZINIT[MAN_DIR]/man1/ ;
      cp -vf man/exa_colors.5 $ZINIT[MAN_DIR]/man5/' \
    ogham/exa \
  atclone'mkdir -p $ZPFX/{bin,man/man1}' \
  dl"$GH_RAW_URL/junegunn/fzf/master/shell/completion.zsh -> _fzf_completion ;
     $GH_RAW_URL/junegunn/fzf/master/man/man1/fzf.1 -> $ZINIT[MAN_DIR]/man1/fzf.1" \
    junegunn/fzf \
  atclone'mkdir -p $ZPFX/{bin,man/man1} ;
      cp -vf ripgrep*/doc/rg.1 $ZINIT[MAN_DIR]/man1/' \
  lbin'!ripgrep*/rg' \
    BurntSushi/ripgrep \
  atclone'mv cheat-linux-amd64 cheat' \
  dl"$GH_RAW_URL/cheat/cheat/master/scripts/cheat.zsh -> _cheat_completion" \
    cheat/cheat \
  atclone'mkdir -p $ZPFX/{bin,man/man1} ;
      cp -vf micro*/micro.1 $ZINIT[MAN_DIR]/man1/' \
    zyedidia/micro
```

### Relevant output
Here's the `zinit` output when installing:
```
Downloading denisidoro/navi…
(Requesting `navi-v2.22.1-aarch64-unknown-linux-gnu.tar.gz'…)
######################################################################## 100.0%                                                               
[ziextract] Unpacking the files from: `navi-v2.22.1-aarch64-unknown-linux-gnu.tar.gz'…
[ziextract] Successfully extracted and assigned +x chmod to the file: navi.
==> linkbin annex: Created navi soft link & set +x on the navi binary
```

Here's the `zsh` output when trying to execute the `aarch64` version of `navi`:
```
$ navi
zsh: exec format error: navi
```

### Operating System & Version

OS: linux-gnu | Vendor: ubuntu | Machine: x86_64 | CPU: x86_64 | Processor: x86_64 | Hardware: x86_64

### Zsh version

zsh 5.9 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

xterm-256color (tilix)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xunop** [comment]
I have the same problem on my x86_64  Arch Linux.

`znit` `gh-r` downloads the wrong arch version for [mcfly](https://github.com/cantino/mcfly). It downloads `mcfly-v0.8.1-aarch64-unknown-linux-gnu.tar.gz`.

Here's the install code ([from mcfly doc](https://github.com/cantino/mcfly#install-by-zinit)):

```
zinit ice lucid wait"0a" from"gh-r" as"program" atload'eval "$(mcfly init zsh)"'
zinit light cantino/mcfly
```

zinit output:

```
Downloading cantino/mcfly…
(Requesting `mcfly-v0.8.1-aarch64-unknown-linux-gnu.tar.gz'…)
####################################################################################################################### 100.0%
[ziextract] Unpacking the files from: `mcfly-v0.8.1-aarch64-unknown-linux-gnu.tar.gz'…
[ziextract] Successfully extracted and assigned +x chmod to the file: mcfly.
```

When I run `mcfly`, `zsh` outputs the following:

```
❯ mcfly
zsh: exec format error: mcfly

mcfly_prompt_command:14: exec format error: /home/xun/.local/share/zinit/plugins/cantino---mcfly/mcfly
```

## Some info
Operating System & Version:

`OS: linux-gnu | Vendor: pc | Machine: x86_64 | CPU: x86_64 | Processor: unknown | Hardware: x86_64`

Zsh version:

zsh 5.9 (x86_64-pc-linux-gnu)

Terminal emulator:

xterm-256color (alacritty)

**Comment by vladdoster** [comment]
@Xunop,

Thank you for reporting! I have added a `mcfly` test.

<img width="1496" alt="Screenshot 2023-08-29 at 20 31 31" src="https://github.com/zdharma-continuum/zinit/assets/10052309/4c880556-07d6-4786-8406-dbe7cecfff36">

**Comment by vladdoster** [comment]
@mojolo,

I have fixed this bug.

<img width="1431" alt="Screenshot 2023-08-29 at 20 34 29" src="https://github.com/zdharma-continuum/zinit/assets/10052309/a631c431-c98a-431a-bcde-7ae2ef7b6ab0">
