### ISSUE TITLE
[bug]: zinit clist -> Unknown subcommand: `clist`

### ISSUE THREAD

**Issue by imhansai** [zdharma-continuum/zinit#569]
### What happened?

An error occurred when executing zinit clist, zinit completions are OK

### Steps to reproduce

$ zinit clist

### Relevant output

```shell
ERROR: Unknown subcommand: `clist` (it should be one of, e.g.: `load`, `snippet`, `update`, `delete`, …, e.g.: `zinit load username/reponame`) or a for-based command body (i.e.: e.g.: `zinit …ice-spec… for …(plugin or snippet) ID-1 ID-2 ⋯⋯…`). See `help` for a more detailed usage information and the list of the subcommands.
```

### Screenshots and recordings

![image](https://github.com/zdharma-continuum/zinit/assets/17228526/cf8c7971-2f04-4175-890b-1a29bfc0fcb5)

### Operating System & Version

OS: darwin22.0 | Vendor: apple | Machine: x86_64 | CPU: x86_64 | Processor: i386 | Hardware: x86_64

### Zsh version

zsh 5.9 (x86_64-apple-darwin22.0)

### Terminal emulator

xterm-256color

### If using WSL on Windows, which version of WSL

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
@imhansai,

Thank you for reporting this! I have opened a PR to fix this.

**Comment by ShelpAm** [comment]
```zi clist``` still prints ```ERROR: Unknown subcommand: `clist` (it should be one of, e.g.: `load`, `snippet`, `update`, `delete`, …, e.g.: `zinit load username/reponame`) or a for-based command body (i.e.: e.g.: `zinit …ice-spec… for …(plugin or snippet) ID-1 ID-2 ⋯⋯…`). See `help` for a more detailed usage information and the list of the subcommands.```

I have updated my zinit to the following version:
```❯ zinit version
zinit v3.12.1-1-g3c7e5be0 (linux-gnu_x86_64)```

**Comment by imhansai** [comment]
@ShelpAm 实际上，命令补全中已经移除了 `clist`, 只能使用 `completions` 子命令
In fact, clist has been removed from command completion, and only the completions subcommand can be used.

![image](https://github.com/zdharma-continuum/zinit/assets/17228526/fca43981-db19-41df-bad0-c96a0ebb306d)

**Comment by ShelpAm** [comment]
@imhansai 谢谢了！
