### ISSUE TITLE
[bug]: OMZP::aliases not functional

### ISSUE THREAD

**Issue by mefengl** [zdharma-continuum/zinit#571]
### What happened?

When I run `als git`, I got:
```
/Users/xx/.pyenv/versions/3.10.10/bin/python3: can't open file '/Users/xx/.local/share/zinit/snippets/OMZP::aliases/cheatsheet.py': [Errno 2] No such file or directory
```

It should show the git's aliases, as in oh-my-zsh.

### Steps to reproduce

```
# ~/.zshrc
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

zinit wait lucid for OMZP::aliases

zinit for \
    atload"zicompinit; zicdreplay" \
    blockf \
    lucid \
    wait \
  zsh-users/zsh-completions
```

### Operating System & Version

OS: darwin22.0 | Vendor: apple | Machine: x86_64 | CPU: arm64 | Processor: arm | Hardware: arm64

### Zsh version

zsh 5.9 (x86_64-apple-darwin22.0)

### Terminal emulator

xterm-256color

### If using WSL on Windows, which version of WSL

None

### Additional context

https://github.com/zdharma-continuum/zinit/issues/481
I wonder if this issue means that it can now work without svn, but I don't know how to do it.

Also, there is a solution provided that I am currently using which comes from `zi`:
https://github.com/z-shell/zi/issues/257

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
@mefengl,

The `{OMZ,PZT}::` notation and `snippet` ice notation will download a single file (i.e., a snippet) because most plugins are a single file. This breaks the `aliases` plugin (and a few others) because it relies on other files. Using the `svn` will leverage subversions and download the whole plugin directory. 

You can use the following recipe:

```zsh
zinit ice svn
zinit snippet OMZ::plugins/aliases
```

<img width="738" alt="Screenshot 2023-09-01 at 17 57 11" src="https://github.com/zdharma-continuum/zinit/assets/10052309/f8d72c1d-0a09-46e4-aafa-403af2bebbd0">

**Comment by mefengl** [comment]
> https://github.com/zdharma-continuum/zinit/issues/481
I wonder if this issue means that it can now work without svn, but I don't know how to do it.
> 
> Also, there is a solution provided that I am currently using which comes from `zi`:
https://github.com/z-shell/zi/issues/257

Thanks for the reply. I also mentioned this SVN solution in my issue. What I am asking for is a solution without SVN.

Thanks again for the reply. If this is the solution for the current issue, I guess we can close it as not planned.
