### ISSUE TITLE
Remove all unicode emojis / symbols from file names

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/zinit#58]
**Describe the bug**
Zinit cannot compile annex since some of the handler files have unicode chars in their names which `zcompile` [does not support](https://www.zsh.org/mla/workers/2020/msg01057.html).
I wonder if we can dance around this issue by making the `compile` ice dynamically rename files.

**Zinit config**
```zsh
zinit light-mode compile'*handler' for \
     zdharma-continuum/zinit-annex-bin-gem-node
```

**Error output**

```
(anon):zcompile:2: can't open file: /home/pschmitt/.local/share/zinit/plugins/zdharma-continuum---zinit-annex-bin-gem-node/\M-b\M-^F\M-^Rza-bgn-atclone-handler                                         
(anon):zcompile:2: can't open file: /home/pschmitt/.local/share/zinit/plugins/zdharma-continuum---zinit-annex-bin-gem-node/\M-b\M-^F\M-^Rza-bgn-atdelete-handler                                        
(anon):zcompile:2: can't open file: /home/pschmitt/.local/share/zinit/plugins/zdharma-continuum---zinit-annex-bin-gem-node/\M-b\M-^F\M-^Rza-bgn-atload-handler                                          
(anon):zcompile:2: can't open file: /home/pschmitt/.local/share/zinit/plugins/zdharma-continuum---zinit-annex-bin-gem-node/\M-b\M-^F\M-^Rza-bgn-help-handler
```

**Comment by vladdoster** [comment]
I don't think Unicode is the issue here

**Comment by pschmitt** [comment]
Why? Got a theory on that?

**Comment by vladdoster** [comment]
Did I think they already had Unicode in their name? Such as `zinit-annex-patch-dl`?

**Comment by pschmitt** [comment]
> Did I think they already had Unicode in their name? Such as `zinit-annex-patch-dl`?

Most of them have one or more zsh files that contain a unicode arrow (→) in their name.

The obvious fix is to rename these files in the annex repos. This might be the cleaner way of handling this.

Is there anything preventing us from doing so? 🤔

**Comment by alichtman** [comment]
I don’t think so. Happy to get rid of the arrow.

**Comment by docwhat** [comment]
This is actually a known bug is zsh:  https://www.zsh.org/mla/workers/2020/msg01058.html

**Comment by alichtman** [comment]
Regardless of the root cause, I think the right fix is to remove Unicode arrows from filenames. They cause more trouble than they're worth.

**Comment by pschmitt** [comment]
:point_up_2:  It has begun!

**Comment by pschmitt** [comment]
And now it's done! 🏆

**Comment by ryaminal** [comment]
this seems to have horked over a few of my zinit steps. error:
```bash
Updating Schniz/fnm…
Binary release already up to date (version: v1.28.1)
[update] Continuing with the update because run-atpull'' ice given.
No files for compilation found.
(eval):1: →za-patch-dl-handler: function definition file not found
(eval):1: →za-submods-atpull-handler: function definition file not found
(eval):1: →za-rust-atclone-handler: function definition file not found
(eval):1: →za-bgn-atclone-handler: function definition file not found
```
anyone know of a fix that doesn't include wiping my zinit install and starting it over?

**Comment by pschmitt** [comment]
Are you using the module?
Do you still have `zwc` files laying around in there?

Reinstalling zinit itself won't be needed here in, re-installing the annex might help though.

**Comment by ryaminal** [comment]
In the end it was much more cumbersome to find all locations and i ended up just wiping zinit entirely.

i also stumbled upon [this](https://github.com/zdharma-continuum/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#standard-recommended-variables) which explains why the arrow was used. i think it was hasty to remove the arrow entirely without understanding why it was there.
