### ISSUE TITLE
💡Proposal: Migration script?

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/zinit#62]
To enable an easy and painless migration for the deleted zdharma, zsh-packages, zsh-zinit and psprint repos we should consider investing the time into creating either:

- a one of script that would edit all the remotes of any affected pługins
- Update `zinit self-update` to do that perhaps?

The issues I see with either approach are the following:

- ⚠️ we shouldn't touch the users config file(s). Depending on the setup this might be very tricky to do anyway. A plugin report should be enough.
- is it even worth the effort? Assuming most of the user-base that's left has already done the migration manually.

> Maybe we should provide a script to do this automagically.

_Originally posted by @pschmitt in https://github.com/zdharma-continuum/zinit/issues/28#issuecomment-968365923_

**Comment by mys721tx** [comment]
A notice on the affected repos should suffice. As soon as the user updates their `.zshrc`, the new package will be downloaded as missing packages on the next time it is loaded.

**Comment by alichtman** [comment]
Setting up zsh configuration files is incredibly user-specific. My setup looks absolutely nothing like the "default" install. I think that this is probably not worthwhile. Worst case, the user blows away their current zinit install and installs fresh following our guide.

> is it even worth the effort? Assuming most of the user-base that's left has already done the migration manually.

I'd say no.
