### ISSUE TITLE
Automatic install failed on MacOS

### ISSUE THREAD

**Issue by mint-rabi** [zdharma-continuum/zinit#64]
**Describe the bug**
When I run Automatic Install, the "mktemp" command exits with illegal options.

**Zinit config**
No

**Expected behavior**
Automatic install success.

**Screenshots (optional)**
No

**Versions:**
 - $ZSH_VERSION == zsh 5.8 (x86_64-apple-darwin20.0)
 - Operating system name and version (uname -a): Darwin mintrabi.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

**Additional context**
#43

**Comment by alichtman** [comment]
Can you paste the error output?

**Comment by mint-rabi** [comment]
Yes!
```
% sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/master/doc/install.sh)"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/master/doc/install.sh)"
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
Tempdir creation failed. This ain't good.
```

**Comment by seagle0128** [comment]
Just use `mktemp -d` instead of `mktemp --directory`.

**Comment by alichtman** [comment]
> Just use `mktemp -d` instead of `mktemp --directory`.

For scripts that will be read and edited over and over, explicit is better than shorthand.

**Comment by alichtman** [comment]
> Just use `mktemp -d` instead of `mktemp --directory`.

Edit: yeah, should work. Ignore my previous comment, doesn't apply in this context

**Comment by pschmitt** [comment]
That one is on me.

To redeem myself I've added a CI workflow to #61 to test the installer on linux and macOS

**Comment by alichtman** [comment]
+1 for better CI. Mistakes happen, good to catch them early
