### ISSUE TITLE
💡 Proposal: Move the C module to another repo

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/zinit#68]
To me at least the module deserves to be hosted in its own repo, esp. since it is neither a strict dependency of zinit, nor does it require zinit to be installed. Unix philosophy and all.

It does not make sense to have it lay around here. Even the annexes us separate repos after all.

TODO:
- [ ] Find a fitting name for the module (maybe not "zinit-module") 
- [x] Create a new repo w/ code and relevant README (https://github.com/zdharma-continuum/zinit-module)
- [ ] Update `zinit module build` so that it fetches the source from the other repo
- [ ] Remove the module from zinit's repo (`./zmodules`)
- [ ] README.md: Link to new repo
- [ ] Update `doc/CHANGELOG.md`

Related: #36

**Comment by docwhat** [comment]
What does the c-module actually do?

**Comment by Monory** [comment]
It does two things, mostly:
1. (useful standalone) with module loaded, each .zsh file sourced will be transparently compiled to .zwc in the background, so the next startup will be faster
2. (less so) tracks the time it took to source each file, to assist `zinit times` better

**Comment by docwhat** [comment]
So Zinit doesn't actually require this?

How about contributing upstream to Zsh?  That way everyone can benefit.

**Comment by alichtman** [comment]
My understanding is that the C module contributes to zinit's speed. It is "necessary" in that respect. 

We could conceivably contribute it to upstream zsh, although I don't have concrete implementation details for how this would work.

**Comment by pschmitt** [comment]
> So Zinit doesn't actually require this?

No. It does not. That's exactly why I created this issue :)
The module is 100% optional, just like annexes are.

> How about contributing upstream to Zsh? That way everyone can benefit.

That's the way to go. Personally don't have the time for that, at all. And I don't do C code, which is also part of the reason why I want to host the module outside of zinit's core.
In its current state, the module is not upstreamable - whether it is part of zinit or not.

 > My understanding is that the C module contributes to zinit's speed. It is "necessary" in that respect.

While this *can* be true, it isn't necessarily. The module does not strictly speaking speed things up, it's nothing more than a glorified `compile'**'`.

I've ran zinit w/o the module for years, the module is entirely optional and only enables niche use-cases.

Also please keep in mind that I am not advocating for nuking the module out of existence.
It's about moving it over to a (in my opinion) more suitable place.

**Comment by pschmitt** [comment]
Closed by #71
