### ISSUE TITLE
💡 Proposal: Merge all zinit-package repos into one

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/zinit#69]
First and foremost: NICE.
Anyway here's me again, with another proposal. 

To manage zinit packages more easily I'd like to merge all of the zinit-package-* repos into one single mono-repo.
Here's why:

- the package repos only host a single `package.json` file
- unlike plugins, packages do not get (git) cloned when installing them
- it would increase zinit packages discoverability to only have to look for packages in a single repo
- development and especially refactoring will be easier in the future. No need to update 10+ repos anymore if anything changes in the `package.json` format for example. (Example: https://github.com/zdharma-continuum/zinit-packages/commit/630c49cb97672fbc16b5886beff8585e578ee6d7)
- the README of https://github.com/zdharma-continuum/zinit-packages would be the perfect place to put documentation about how to create a package. Currently, it is pretty much split across all the repos.

Per repo TODO:

- [x] Move files to https://github.com/zdharma-continuum/zinit-packages into a subdir named after the package name
- [x] Update the README in the respective repo to inform users that development continues in https://github.com/zdharma-continuum/zinit-packages
- [ ] Debatable: Add deprecation notice right in the `atclone` ices?
- [x] Archive the repo

zinit TODO:

- [x] Edit the URL that zinit uses to fetch `package.json`
- [x] Add depreciation notice in `README.md` and `doc/CHANGELOG.md`

Migration status:

- [x] https://github.com/zdharma-continuum/zinit-package-any-gem
- [x] https://github.com/zdharma-continuum/zinit-package-any-node
- [x] https://github.com/zdharma-continuum/zinit-package-apr
- [x] https://github.com/zdharma-continuum/zinit-package-asciidoctor
- [x] https://github.com/zdharma-continuum/zinit-package-dircolors-material
- [x] https://github.com/zdharma-continuum/zinit-package-doctoc
- [x] https://github.com/zdharma-continuum/zinit-package-ecs-cli
- [x] https://github.com/zdharma-continuum/zinit-package-firefox-dev
- [x] https://github.com/zdharma-continuum/zinit-package-fzf
- [x] https://github.com/zdharma-continuum/zinit-package-fzy
- [x] https://github.com/zdharma-continuum/zinit-package-github-issues
- [x] https://github.com/zdharma-continuum/zinit-package-github-issues-srv
- [x] https://github.com/zdharma-continuum/zinit-package-ls_colors
- [x] https://github.com/zdharma-continuum/zinit-package-pyenv
- [x] https://github.com/zdharma-continuum/zinit-package-remark
- [x] https://github.com/zdharma-continuum/zinit-package-svn
- [x] https://github.com/zdharma-continuum/zinit-package-system-completions
- [x] https://github.com/zdharma-continuum/zinit-package-zsh
- [x] https://github.com/zdharma-continuum/zinit-package-zsh-static

**Comment by pschmitt** [comment]
Updating the ices to display a scary warning is not necessary, and up-to-date zinit will just use to the new repo.

The legacy repos have been archived and can therefore still be used by older zinit versions.

**Comment by alichtman** [comment]
This is a great improvement. Thanks @pschmitt!
