### ISSUE TITLE
Add CI test for installing packages / programs

### ISSUE THREAD

**Issue by alichtman** [zdharma-continuum/zinit#77]
From:

- [ ] GitHub Releases
- [ ]  zinit-packages monorepo
- [ ] Oh-My-zsh

**Comment by alichtman** [comment]
nvm, just found the `test` branch. How about we bring that over onto `master` and put it in a `tests` folder or something.

**Comment by pschmitt** [comment]
Yeah, see https://github.com/zdharma-continuum/zinit/pull/37 and https://github.com/zdharma-continuum/zinit/pull/42.

In all fairness, the tests are in a pretty bad state right now. Haven't looked into that yet, besides the usual `s/zplugin/zinit`.
We may be better off dropping that branch and starting from scratch.

**Comment by pschmitt** [comment]
> How about we bring that over onto master and put it in a tests folder or something.

See https://github.com/zdharma-continuum/zinit/issues/36

**Comment by pschmitt** [comment]
https://github.com/pschmitt/zinit/runs/4273230368?check_suite_focus=true

👀
