### ISSUE TITLE
💡 Proposal: Sever the link between our forked repos and their parents

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/zinit#81]
Have to admit, the title is weird.

Anyway we, zdharma-continuum, host a whole bunch of forked repos. AFAIK these were all created after the "deletening" (yes, I'm trying to make this is thing).

Some if not all of these forks have received updates. I don't think we'll ever "upstream" those changes back by opening PRs towards the original repos.
So, to improve discoverability and make our repo stand out a bit more we should IMHO get in touch with GH support to ask them to remove this "fork" relationship.

List of forks: https://github.com/orgs/zdharma-continuum/repositories?q=&type=fork&language=&sort=

TODO:

- [x] https://github.com/zdharma-continuum/zsh-startify
- [x] https://github.com/zdharma-continuum/zsh-navigation-tools
- [x] https://github.com/zdharma-continuum/zbrowse
- [ ] https://github.com/zdharma-continuum/zzcomplete
- [ ] https://github.com/zdharma-continuum/zconvey
- [ ] https://github.com/zdharma-continuum/zui
- [ ] https://github.com/zdharma-continuum/zinit-annex-unscope
- [ ] https://github.com/zdharma-continuum/zinit-annex-submods
- [ ] https://github.com/zdharma-continuum/zinit-annex-rust
- [ ] https://github.com/zdharma-continuum/zinit-annex-patch-dl
- [ ] https://github.com/zdharma-continuum/zinit-annex-meta-plugins
- [ ] https://github.com/zdharma-continuum/zinit-annex-test
- [ ] https://github.com/zdharma-continuum/zinit-annex-bin-gem-node
- [x] https://github.com/zdharma-continuum/zinit-annex-readurl
- [ ] https://github.com/zdharma-continuum/zservice-redis
- [ ] https://github.com/zdharma-continuum/zsh-github-issues
- [ ] https://github.com/zdharma-continuum/Zsh-100-Commits-Club
- [ ] https://github.com/zdharma-continuum/zinit-crasis
- [ ] https://github.com/zdharma-continuum/zinit-configs
- [ ] https://github.com/zdharma-continuum/zinit-console
- [ ] https://github.com/zdharma-continuum/zsh-tig-plugin
- [ ] https://github.com/zdharma-continuum/zsh-lint

**Comment by alichtman** [comment]
Cool by me :)

**Comment by pschmitt** [comment]
Update:

- the support assistant bot has a request quota - which I very quickly reached.
- but! It turns out you can provide a list of repos in a single ticket. Though I needed to create a ticket per repo :facepalm: 

Anyway, this should be done soon :)

**Comment by pschmitt** [comment]
Done!

https://support.github.com/ticket/personal/0/1400971
